<!-- begin of generated class -->
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        invoicedetail
* GENERATION DATE:  17.09.2017
* CLASS FILE:       C:\wamp64\www\genera_clase/generated_classes/class.invoicedetail.php
* FOR MYSQL TABLE:  invoicelinedetail
* FOR MYSQL DB:     dbaurora
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* modify: >> www.aurora-ec.net >> (download for free!)
* -------------------------------------------------------
*
*/
include_once("class.aurora.php");
// **********************
// CLASS DECLARATION
// **********************

class invoicedetail
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************


public $TxnLineID;   // (normal Attribute)
public $ItemRef_ListID;   // (normal Attribute)
public $ItemRef_FullName;   // (normal Attribute)
public $Description;   // (normal Attribute)
public $Quantity;   // (normal Attribute)
public $UnitOfMeasure;   // (normal Attribute)
public $OverrideUOMSetRef_ListID;   // (normal Attribute)
public $OverrideUOMSetRef_FullName;   // (normal Attribute)
public $Rate;   // (normal Attribute)
public $RatePercent;   // (normal Attribute)
public $ClassRef_ListID;   // (normal Attribute)
public $ClassRef_FullName;   // (normal Attribute)
public $Amount;   // (normal Attribute)
public $InventorySiteRef_ListID;   // (normal Attribute)
public $InventorySiteRef_FullName;   // (normal Attribute)
public $InventorySiteLocationRef_ListID;   // (normal Attribute)
public $InventorySiteLocationRef_FullName;   // (normal Attribute)
public $SerialNumber;   // (normal Attribute)
public $LotNumber;   // (normal Attribute)
public $ServiceDate;   // (normal Attribute)
public $SalesTaxCodeRef_ListID;   // (normal Attribute)
public $SalesTaxCodeRef_FullName;   // (normal Attribute)
public $Other1;   // (normal Attribute)
public $Other2;   // (normal Attribute)
public $LinkedTxnID;   // (normal Attribute)
public $LinkedTxnLineID;   // (normal Attribute)
public $CustomField1;   // (normal Attribute)
public $CustomField2;   // (normal Attribute)
public $CustomField3;   // (normal Attribute)
public $CustomField4;   // (normal Attribute)
public $CustomField5;   // (normal Attribute)
public $CustomField6;   // (normal Attribute)
public $CustomField7;   // (normal Attribute)
public $CustomField8;   // (normal Attribute)
public $CustomField9;   // (normal Attribute)
public $CustomField10;   // (normal Attribute)
public $CustomField11;   // (normal Attribute)
public $CustomField12;   // (normal Attribute)
public $CustomField13;   // (normal Attribute)
public $CustomField14;   // (normal Attribute)
public $CustomField15;   // (normal Attribute)
public $IDKEY;   // (normal Attribute)
public $GroupIDKEY;   // (normal Attribute)

var $db; // Instance of class database


// **********************
// CONSTRUCTOR METHOD
// **********************

function __construct()
{

$this->db = conecta_PDO();
}

function __destruct()
{


}

function genJson_invoicedetail($jsonString)
{
$_SESSION['invoicedetail']['TxnLineID'] = $jsonString->TxnLineID;
$_SESSION['invoicedetail']['ItemRef_ListID'] = $jsonString->ItemRef_ListID;
$_SESSION['invoicedetail']['ItemRef_FullName'] = $jsonString->ItemRef_FullName;
$_SESSION['invoicedetail']['Description'] = $jsonString->Description;
$_SESSION['invoicedetail']['Quantity'] = $jsonString->Quantity;
$_SESSION['invoicedetail']['UnitOfMeasure'] = $jsonString->UnitOfMeasure;
$_SESSION['invoicedetail']['OverrideUOMSetRef_ListID'] = $jsonString->OverrideUOMSetRef_ListID;
$_SESSION['invoicedetail']['OverrideUOMSetRef_FullName'] = $jsonString->OverrideUOMSetRef_FullName;
$_SESSION['invoicedetail']['Rate'] = $jsonString->Rate;
$_SESSION['invoicedetail']['RatePercent'] = $jsonString->RatePercent;
$_SESSION['invoicedetail']['ClassRef_ListID'] = $jsonString->ClassRef_ListID;
$_SESSION['invoicedetail']['ClassRef_FullName'] = $jsonString->ClassRef_FullName;
$_SESSION['invoicedetail']['Amount'] = $jsonString->Amount;
$_SESSION['invoicedetail']['InventorySiteRef_ListID'] = $jsonString->InventorySiteRef_ListID;
$_SESSION['invoicedetail']['InventorySiteRef_FullName'] = $jsonString->InventorySiteRef_FullName;
$_SESSION['invoicedetail']['InventorySiteLocationRef_ListID'] = $jsonString->InventorySiteLocationRef_ListID;
$_SESSION['invoicedetail']['InventorySiteLocationRef_FullName'] = $jsonString->InventorySiteLocationRef_FullName;
$_SESSION['invoicedetail']['SerialNumber'] = $jsonString->SerialNumber;
$_SESSION['invoicedetail']['LotNumber'] = $jsonString->LotNumber;
$_SESSION['invoicedetail']['ServiceDate'] = $jsonString->ServiceDate;
$_SESSION['invoicedetail']['SalesTaxCodeRef_ListID'] = $jsonString->SalesTaxCodeRef_ListID;
$_SESSION['invoicedetail']['SalesTaxCodeRef_FullName'] = $jsonString->SalesTaxCodeRef_FullName;
$_SESSION['invoicedetail']['Other1'] = $jsonString->Other1;
$_SESSION['invoicedetail']['Other2'] = $jsonString->Other2;
$_SESSION['invoicedetail']['LinkedTxnID'] = $jsonString->LinkedTxnID;
$_SESSION['invoicedetail']['LinkedTxnLineID'] = $jsonString->LinkedTxnLineID;
$_SESSION['invoicedetail']['CustomField1'] = $jsonString->CustomField1;
$_SESSION['invoicedetail']['CustomField2'] = $jsonString->CustomField2;
$_SESSION['invoicedetail']['CustomField3'] = $jsonString->CustomField3;
$_SESSION['invoicedetail']['CustomField4'] = $jsonString->CustomField4;
$_SESSION['invoicedetail']['CustomField5'] = $jsonString->CustomField5;
$_SESSION['invoicedetail']['CustomField6'] = $jsonString->CustomField6;
$_SESSION['invoicedetail']['CustomField7'] = $jsonString->CustomField7;
$_SESSION['invoicedetail']['CustomField8'] = $jsonString->CustomField8;
$_SESSION['invoicedetail']['CustomField9'] = $jsonString->CustomField9;
$_SESSION['invoicedetail']['CustomField10'] = $jsonString->CustomField10;
$_SESSION['invoicedetail']['CustomField11'] = $jsonString->CustomField11;
$_SESSION['invoicedetail']['CustomField12'] = $jsonString->CustomField12;
$_SESSION['invoicedetail']['CustomField13'] = $jsonString->CustomField13;
$_SESSION['invoicedetail']['CustomField14'] = $jsonString->CustomField14;
$_SESSION['invoicedetail']['CustomField15'] = $jsonString->CustomField15;
$_SESSION['invoicedetail']['IDKEY'] = $jsonString->IDKEY;
$_SESSION['invoicedetail']['GroupIDKEY'] = $jsonString->GroupIDKEY;

}

function genInsert_invoicedetail()
{
$this->setTxnLineID($_SESSION['invoicedetail']['TxnLineID']);
$this->setItemRef_ListID($_SESSION['invoicedetail']['ItemRef_ListID']);
$this->setItemRef_FullName($_SESSION['invoicedetail']['ItemRef_FullName']);
$this->setDescription($_SESSION['invoicedetail']['Description']);
$this->setQuantity($_SESSION['invoicedetail']['Quantity']);
$this->setUnitOfMeasure($_SESSION['invoicedetail']['UnitOfMeasure']);
$this->setOverrideUOMSetRef_ListID($_SESSION['invoicedetail']['OverrideUOMSetRef_ListID']);
$this->setOverrideUOMSetRef_FullName($_SESSION['invoicedetail']['OverrideUOMSetRef_FullName']);
$this->setRate($_SESSION['invoicedetail']['Rate']);
$this->setRatePercent($_SESSION['invoicedetail']['RatePercent']);
$this->setClassRef_ListID($_SESSION['invoicedetail']['ClassRef_ListID']);
$this->setClassRef_FullName($_SESSION['invoicedetail']['ClassRef_FullName']);
$this->setAmount($_SESSION['invoicedetail']['Amount']);
$this->setInventorySiteRef_ListID($_SESSION['invoicedetail']['InventorySiteRef_ListID']);
$this->setInventorySiteRef_FullName($_SESSION['invoicedetail']['InventorySiteRef_FullName']);
$this->setInventorySiteLocationRef_ListID($_SESSION['invoicedetail']['InventorySiteLocationRef_ListID']);
$this->setInventorySiteLocationRef_FullName($_SESSION['invoicedetail']['InventorySiteLocationRef_FullName']);
$this->setSerialNumber($_SESSION['invoicedetail']['SerialNumber']);
$this->setLotNumber($_SESSION['invoicedetail']['LotNumber']);
$this->setServiceDate($_SESSION['invoicedetail']['ServiceDate']);
$this->setSalesTaxCodeRef_ListID($_SESSION['invoicedetail']['SalesTaxCodeRef_ListID']);
$this->setSalesTaxCodeRef_FullName($_SESSION['invoicedetail']['SalesTaxCodeRef_FullName']);
$this->setOther1($_SESSION['invoicedetail']['Other1']);
$this->setOther2($_SESSION['invoicedetail']['Other2']);
$this->setLinkedTxnID($_SESSION['invoicedetail']['LinkedTxnID']);
$this->setLinkedTxnLineID($_SESSION['invoicedetail']['LinkedTxnLineID']);
$this->setCustomField1($_SESSION['invoicedetail']['CustomField1']);
$this->setCustomField2($_SESSION['invoicedetail']['CustomField2']);
$this->setCustomField3($_SESSION['invoicedetail']['CustomField3']);
$this->setCustomField4($_SESSION['invoicedetail']['CustomField4']);
$this->setCustomField5($_SESSION['invoicedetail']['CustomField5']);
$this->setCustomField6($_SESSION['invoicedetail']['CustomField6']);
$this->setCustomField7($_SESSION['invoicedetail']['CustomField7']);
$this->setCustomField8($_SESSION['invoicedetail']['CustomField8']);
$this->setCustomField9($_SESSION['invoicedetail']['CustomField9']);
$this->setCustomField10($_SESSION['invoicedetail']['CustomField10']);
$this->setCustomField11($_SESSION['invoicedetail']['CustomField11']);
$this->setCustomField12($_SESSION['invoicedetail']['CustomField12']);
$this->setCustomField13($_SESSION['invoicedetail']['CustomField13']);
$this->setCustomField14($_SESSION['invoicedetail']['CustomField14']);
$this->setCustomField15($_SESSION['invoicedetail']['CustomField15']);
//$this->setIDKEY($_SESSION['invoice']['TxnID']);
//$this->setGroupIDKEY($_SESSION['invoicedetail']['GroupIDKEY']);

}

function genLimpia_invoicedetail()
{
$_SESSION['invoicedetail']['TxnLineID'] = ' ';
$_SESSION['invoicedetail']['ItemRef_ListID'] = ' ';
$_SESSION['invoicedetail']['ItemRef_FullName'] = ' ';
$_SESSION['invoicedetail']['Description'] = ' ';
$_SESSION['invoicedetail']['Quantity'] = ' ';
$_SESSION['invoicedetail']['UnitOfMeasure'] = ' ';
$_SESSION['invoicedetail']['OverrideUOMSetRef_ListID'] = ' ';
$_SESSION['invoicedetail']['OverrideUOMSetRef_FullName'] = ' ';
$_SESSION['invoicedetail']['Rate'] = ' ';
$_SESSION['invoicedetail']['RatePercent'] = ' ';
$_SESSION['invoicedetail']['ClassRef_ListID'] = ' ';
$_SESSION['invoicedetail']['ClassRef_FullName'] = ' ';
$_SESSION['invoicedetail']['Amount'] = ' ';
$_SESSION['invoicedetail']['InventorySiteRef_ListID'] = ' ';
$_SESSION['invoicedetail']['InventorySiteRef_FullName'] = ' ';
$_SESSION['invoicedetail']['InventorySiteLocationRef_ListID'] = ' ';
$_SESSION['invoicedetail']['InventorySiteLocationRef_FullName'] = ' ';
$_SESSION['invoicedetail']['SerialNumber'] = ' ';
$_SESSION['invoicedetail']['LotNumber'] = ' ';
$_SESSION['invoicedetail']['ServiceDate'] = ' ';
$_SESSION['invoicedetail']['SalesTaxCodeRef_ListID'] = ' ';
$_SESSION['invoicedetail']['SalesTaxCodeRef_FullName'] = ' ';
$_SESSION['invoicedetail']['Other1'] = ' ';
$_SESSION['invoicedetail']['Other2'] = ' ';
$_SESSION['invoicedetail']['LinkedTxnID'] = ' ';
$_SESSION['invoicedetail']['LinkedTxnLineID'] = ' ';
$_SESSION['invoicedetail']['CustomField1'] = ' ';
$_SESSION['invoicedetail']['CustomField2'] = ' ';
$_SESSION['invoicedetail']['CustomField3'] = ' ';
$_SESSION['invoicedetail']['CustomField4'] = ' ';
$_SESSION['invoicedetail']['CustomField5'] = ' ';
$_SESSION['invoicedetail']['CustomField6'] = ' ';
$_SESSION['invoicedetail']['CustomField7'] = ' ';
$_SESSION['invoicedetail']['CustomField8'] = ' ';
$_SESSION['invoicedetail']['CustomField9'] = ' ';
$_SESSION['invoicedetail']['CustomField10'] = ' ';
$_SESSION['invoicedetail']['CustomField11'] = ' ';
$_SESSION['invoicedetail']['CustomField12'] = ' ';
$_SESSION['invoicedetail']['CustomField13'] = ' ';
$_SESSION['invoicedetail']['CustomField14'] = ' ';
$_SESSION['invoicedetail']['CustomField15'] = ' ';
$_SESSION['invoicedetail']['IDKEY'] = ' ';
$_SESSION['invoicedetail']['GroupIDKEY'] = ' ';

}

function gentraverse_invoicedetail($node)
{
$node->getElementsByTagName('TxnLineID')->item(0) === NULL ? $_SESSION['invoicedetail']['TxnLineID'] = ' ' : $_SESSION['invoicedetail']['TxnLineID'] = $node->getElementsByTagName('TxnLineID')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(0) === NULL ? $_SESSION['invoicedetail']['ItemRef_ListID'] = ' ' : $_SESSION['invoicedetail']['ItemRef_ListID'] = $node->getElementsByTagName('ListID')->item(0)->nodeValue;
$node->getElementsByTagName('FullName')->item(0) === NULL ? $_SESSION['invoicedetail']['ItemRef_FullName'] = ' ' : $_SESSION['invoicedetail']['ItemRef_FullName'] = $node->getElementsByTagName('FullName')->item(0)->nodeValue;
$node->getElementsByTagName('Description')->item(0) === NULL ? $_SESSION['invoicedetail']['Description'] = ' ' : $_SESSION['invoicedetail']['Description'] = $node->getElementsByTagName('Description')->item(0)->nodeValue;
$node->getElementsByTagName('Quantity')->item(0) === NULL ? $_SESSION['invoicedetail']['Quantity'] = ' ' : $_SESSION['invoicedetail']['Quantity'] = $node->getElementsByTagName('Quantity')->item(0)->nodeValue;
$node->getElementsByTagName('UnitOfMeasure')->item(0) === NULL ? $_SESSION['invoicedetail']['UnitOfMeasure'] = ' ' : $_SESSION['invoicedetail']['UnitOfMeasure'] = $node->getElementsByTagName('UnitOfMeasure')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(1) === NULL ? $_SESSION['invoicedetail']['OverrideUOMSetRef_ListID'] = ' ' : $_SESSION['invoicedetail']['OverrideUOMSetRef_ListID'] = $node->getElementsByTagName('ListID')->item(1)->nodeValue;
$node->getElementsByTagName('FullName')->item(1) === NULL ? $_SESSION['invoicedetail']['OverrideUOMSetRef_FullName'] = ' ' : $_SESSION['invoicedetail']['OverrideUOMSetRef_FullName'] = $node->getElementsByTagName('FullName')->item(1)->nodeValue;
$node->getElementsByTagName('Rate')->item(0) === NULL ? $_SESSION['invoicedetail']['Rate'] = ' ' : $_SESSION['invoicedetail']['Rate'] = $node->getElementsByTagName('Rate')->item(0)->nodeValue;
$node->getElementsByTagName('RatePercent')->item(0) === NULL ? $_SESSION['invoicedetail']['RatePercent'] = ' ' : $_SESSION['invoicedetail']['RatePercent'] = $node->getElementsByTagName('RatePercent')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(2) === NULL ? $_SESSION['invoicedetail']['ClassRef_ListID'] = ' ' : $_SESSION['invoicedetail']['ClassRef_ListID'] = $node->getElementsByTagName('ListID')->item(2)->nodeValue;
$node->getElementsByTagName('FullName')->item(2) === NULL ? $_SESSION['invoicedetail']['ClassRef_FullName'] = ' ' : $_SESSION['invoicedetail']['ClassRef_FullName'] = $node->getElementsByTagName('FullName')->item(2)->nodeValue;
$node->getElementsByTagName('Amount')->item(0) === NULL ? $_SESSION['invoicedetail']['Amount'] = 0 : $_SESSION['invoicedetail']['Amount'] = $node->getElementsByTagName('Amount')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(3) === NULL ? $_SESSION['invoicedetail']['InventorySiteRef_ListID'] = ' ' : $_SESSION['invoicedetail']['InventorySiteRef_ListID'] = $node->getElementsByTagName('ListID')->item(3)->nodeValue;
$node->getElementsByTagName('FullName')->item(3) === NULL ? $_SESSION['invoicedetail']['InventorySiteRef_FullName'] = ' ' : $_SESSION['invoicedetail']['InventorySiteRef_FullName'] = $node->getElementsByTagName('FullName')->item(3)->nodeValue;
$node->getElementsByTagName('ListID')->item(4) === NULL ? $_SESSION['invoicedetail']['InventorySiteLocationRef_ListID'] = ' ' : $_SESSION['invoicedetail']['InventorySiteLocationRef_ListID'] = $node->getElementsByTagName('ListID')->item(4)->nodeValue;
$node->getElementsByTagName('FullName')->item(4) === NULL ? $_SESSION['invoicedetail']['InventorySiteLocationRef_FullName'] = ' ' : $_SESSION['invoicedetail']['InventorySiteLocationRef_FullName'] = $node->getElementsByTagName('FullName')->item(4)->nodeValue;
$node->getElementsByTagName('SerialNumber')->item(0) === NULL ? $_SESSION['invoicedetail']['SerialNumber'] = ' ' : $_SESSION['invoicedetail']['SerialNumber'] = $node->getElementsByTagName('SerialNumber')->item(0)->nodeValue;
$node->getElementsByTagName('LotNumber')->item(0) === NULL ? $_SESSION['invoicedetail']['LotNumber'] = ' ' : $_SESSION['invoicedetail']['LotNumber'] = $node->getElementsByTagName('LotNumber')->item(0)->nodeValue;
$node->getElementsByTagName('ServiceDate')->item(0) === NULL ? $_SESSION['invoicedetail']['ServiceDate'] = '2010-08-10' : $_SESSION['invoicedetail']['ServiceDate'] = $node->getElementsByTagName('ServiceDate')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(5) === NULL ? $_SESSION['invoicedetail']['SalesTaxCodeRef_ListID'] = ' ' : $_SESSION['invoicedetail']['SalesTaxCodeRef_ListID'] = $node->getElementsByTagName('ListID')->item(5)->nodeValue;
$node->getElementsByTagName('FullName')->item(5) === NULL ? $_SESSION['invoicedetail']['SalesTaxCodeRef_FullName'] = ' ' : $_SESSION['invoicedetail']['SalesTaxCodeRef_FullName'] = $node->getElementsByTagName('FullName')->item(5)->nodeValue;
$node->getElementsByTagName('Other1')->item(0) === NULL ? $_SESSION['invoicedetail']['Other1'] = ' ' : $_SESSION['invoicedetail']['Other1'] = $node->getElementsByTagName('Other1')->item(0)->nodeValue;
$node->getElementsByTagName('Other2')->item(0) === NULL ? $_SESSION['invoicedetail']['Other2'] = ' ' : $_SESSION['invoicedetail']['Other2'] = $node->getElementsByTagName('Other2')->item(0)->nodeValue;
$node->getElementsByTagName('LinkedTxnID')->item(0) === NULL ? $_SESSION['invoicedetail']['LinkedTxnID'] = ' ' : $_SESSION['invoicedetail']['LinkedTxnID'] = $node->getElementsByTagName('LinkedTxnID')->item(0)->nodeValue;
$node->getElementsByTagName('LinkedTxnLineID')->item(0) === NULL ? $_SESSION['invoicedetail']['LinkedTxnLineID'] = ' ' : $_SESSION['invoicedetail']['LinkedTxnLineID'] = $node->getElementsByTagName('LinkedTxnLineID')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField1')->item(0) === NULL ? $_SESSION['invoicedetail']['CustomField1'] = ' ' : $_SESSION['invoicedetail']['CustomField1'] = $node->getElementsByTagName('CustomField1')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField2')->item(0) === NULL ? $_SESSION['invoicedetail']['CustomField2'] = ' ' : $_SESSION['invoicedetail']['CustomField2'] = $node->getElementsByTagName('CustomField2')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField3')->item(0) === NULL ? $_SESSION['invoicedetail']['CustomField3'] = ' ' : $_SESSION['invoicedetail']['CustomField3'] = $node->getElementsByTagName('CustomField3')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField4')->item(0) === NULL ? $_SESSION['invoicedetail']['CustomField4'] = ' ' : $_SESSION['invoicedetail']['CustomField4'] = $node->getElementsByTagName('CustomField4')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField5')->item(0) === NULL ? $_SESSION['invoicedetail']['CustomField5'] = ' ' : $_SESSION['invoicedetail']['CustomField5'] = $node->getElementsByTagName('CustomField5')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField6')->item(0) === NULL ? $_SESSION['invoicedetail']['CustomField6'] = ' ' : $_SESSION['invoicedetail']['CustomField6'] = $node->getElementsByTagName('CustomField6')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField7')->item(0) === NULL ? $_SESSION['invoicedetail']['CustomField7'] = ' ' : $_SESSION['invoicedetail']['CustomField7'] = $node->getElementsByTagName('CustomField7')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField8')->item(0) === NULL ? $_SESSION['invoicedetail']['CustomField8'] = ' ' : $_SESSION['invoicedetail']['CustomField8'] = $node->getElementsByTagName('CustomField8')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField9')->item(0) === NULL ? $_SESSION['invoicedetail']['CustomField9'] = ' ' : $_SESSION['invoicedetail']['CustomField9'] = $node->getElementsByTagName('CustomField9')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField10')->item(0) === NULL ? $_SESSION['invoicedetail']['CustomField10'] = ' ' : $_SESSION['invoicedetail']['CustomField10'] = $node->getElementsByTagName('CustomField10')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField11')->item(0) === NULL ? $_SESSION['invoicedetail']['CustomField11'] = ' ' : $_SESSION['invoicedetail']['CustomField11'] = $node->getElementsByTagName('CustomField11')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField12')->item(0) === NULL ? $_SESSION['invoicedetail']['CustomField12'] = ' ' : $_SESSION['invoicedetail']['CustomField12'] = $node->getElementsByTagName('CustomField12')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField13')->item(0) === NULL ? $_SESSION['invoicedetail']['CustomField13'] = ' ' : $_SESSION['invoicedetail']['CustomField13'] = $node->getElementsByTagName('CustomField13')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField14')->item(0) === NULL ? $_SESSION['invoicedetail']['CustomField14'] = ' ' : $_SESSION['invoicedetail']['CustomField14'] = $node->getElementsByTagName('CustomField14')->item(0)->nodeValue;
$node->getElementsByTagName('CustomField15')->item(0) === NULL ? $_SESSION['invoicedetail']['CustomField15'] = ' ' : $_SESSION['invoicedetail']['CustomField15'] = $node->getElementsByTagName('CustomField15')->item(0)->nodeValue;
//$node->getElementsByTagName('IDKEY')->item(0) === NULL ? $_SESSION['invoicedetail']['IDKEY'] = ' ' : $_SESSION['invoicedetail']['IDKEY'] = $node->getElementsByTagName('IDKEY')->item(0)->nodeValue;
//$node->getElementsByTagName('GroupIDKEY')->item(0) === NULL ? $_SESSION['invoicedetail']['GroupIDKEY'] = ' ' : $_SESSION['invoicedetail']['GroupIDKEY'] = $node->getElementsByTagName('GroupIDKEY')->item(0)->nodeValue;
$node->parentNode->tagName === NULL ?  $_SESSION['invoicedetail']['IDKEY'] = ' ' :  $_SESSION['invoicedetail']['IDKEY'] = substr(ltrim($node->parentNode->nodeValue), 0, 17);
}

function adiciona_invoicedetail()
{
        $this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
try {
    $sql = 'INSERT INTO invoicelinedetail (  TxnLineID, ItemRef_ListID, ItemRef_FullName, Description, Quantity, UnitOfMeasure, OverrideUOMSetRef_ListID, OverrideUOMSetRef_FullName, Rate, RatePercent, ClassRef_ListID, ClassRef_FullName, Amount, InventorySiteRef_ListID, InventorySiteRef_FullName, InventorySiteLocationRef_ListID, InventorySiteLocationRef_FullName, SerialNumber, LotNumber, ServiceDate, SalesTaxCodeRef_ListID, SalesTaxCodeRef_FullName, Other1, Other2, LinkedTxnID, LinkedTxnLineID, CustomField1, CustomField2, CustomField3, CustomField4, CustomField5, CustomField6, CustomField7, CustomField8, CustomField9, CustomField10, CustomField11, CustomField12, CustomField13, CustomField14, CustomField15, IDKEY ) VALUES ( :TxnLineID, :ItemRef_ListID, :ItemRef_FullName, :Description, :Quantity, :UnitOfMeasure, :OverrideUOMSetRef_ListID, :OverrideUOMSetRef_FullName, :Rate, :RatePercent, :ClassRef_ListID, :ClassRef_FullName, :Amount, :InventorySiteRef_ListID, :InventorySiteRef_FullName, :InventorySiteLocationRef_ListID, :InventorySiteLocationRef_FullName, :SerialNumber, :LotNumber, :ServiceDate, :SalesTaxCodeRef_ListID, :SalesTaxCodeRef_FullName, :Other1, :Other2, :LinkedTxnID, :LinkedTxnLineID, :CustomField1, :CustomField2, :CustomField3, :CustomField4, :CustomField5, :CustomField6, :CustomField7, :CustomField8, :CustomField9, :CustomField10, :CustomField11, :CustomField12, :CustomField13, :CustomField14, :CustomField15, :IDKEY )';
$stmt = $this->db->prepare($sql);
 $stmt->bindParam(':TxnLineID', $_SESSION['invoicedetail']['TxnLineID'] );
$stmt->bindParam(':ItemRef_ListID', $_SESSION['invoicedetail']['ItemRef_ListID'] );
$stmt->bindParam(':ItemRef_FullName', $_SESSION['invoicedetail']['ItemRef_FullName'] );
$stmt->bindParam(':Description', $_SESSION['invoicedetail']['Description'] );
$stmt->bindParam(':Quantity', $_SESSION['invoicedetail']['Quantity'] );
$stmt->bindParam(':UnitOfMeasure', $_SESSION['invoicedetail']['UnitOfMeasure'] );
$stmt->bindParam(':OverrideUOMSetRef_ListID', $_SESSION['invoicedetail']['OverrideUOMSetRef_ListID'] );
$stmt->bindParam(':OverrideUOMSetRef_FullName', $_SESSION['invoicedetail']['OverrideUOMSetRef_FullName'] );
$stmt->bindParam(':Rate', $_SESSION['invoicedetail']['Rate'] );
$stmt->bindParam(':RatePercent', $_SESSION['invoicedetail']['RatePercent'] );
$stmt->bindParam(':ClassRef_ListID', $_SESSION['invoicedetail']['ClassRef_ListID'] );
$stmt->bindParam(':ClassRef_FullName', $_SESSION['invoicedetail']['ClassRef_FullName'] );
$stmt->bindParam(':Amount', $_SESSION['invoicedetail']['Amount'] );
$stmt->bindParam(':InventorySiteRef_ListID', $_SESSION['invoicedetail']['InventorySiteRef_ListID'] );
$stmt->bindParam(':InventorySiteRef_FullName', $_SESSION['invoicedetail']['InventorySiteRef_FullName'] );
$stmt->bindParam(':InventorySiteLocationRef_ListID', $_SESSION['invoicedetail']['InventorySiteLocationRef_ListID'] );
$stmt->bindParam(':InventorySiteLocationRef_FullName', $_SESSION['invoicedetail']['InventorySiteLocationRef_FullName'] );
$stmt->bindParam(':SerialNumber', $_SESSION['invoicedetail']['SerialNumber'] );
$stmt->bindParam(':LotNumber', $_SESSION['invoicedetail']['LotNumber'] );
$stmt->bindParam(':ServiceDate', $_SESSION['invoicedetail']['ServiceDate'] );
$stmt->bindParam(':SalesTaxCodeRef_ListID', $_SESSION['invoicedetail']['SalesTaxCodeRef_ListID'] );
$stmt->bindParam(':SalesTaxCodeRef_FullName', $_SESSION['invoicedetail']['SalesTaxCodeRef_FullName'] );
$stmt->bindParam(':Other1', $_SESSION['invoicedetail']['Other1'] );
$stmt->bindParam(':Other2', $_SESSION['invoicedetail']['Other2'] );
$stmt->bindParam(':LinkedTxnID', $_SESSION['invoicedetail']['LinkedTxnID'] );
$stmt->bindParam(':LinkedTxnLineID', $_SESSION['invoicedetail']['LinkedTxnLineID'] );
$stmt->bindParam(':CustomField1', $_SESSION['invoicedetail']['CustomField1'] );
$stmt->bindParam(':CustomField2', $_SESSION['invoicedetail']['CustomField2'] );
$stmt->bindParam(':CustomField3', $_SESSION['invoicedetail']['CustomField3'] );
$stmt->bindParam(':CustomField4', $_SESSION['invoicedetail']['CustomField4'] );
$stmt->bindParam(':CustomField5', $_SESSION['invoicedetail']['CustomField5'] );
$stmt->bindParam(':CustomField6', $_SESSION['invoicedetail']['CustomField6'] );
$stmt->bindParam(':CustomField7', $_SESSION['invoicedetail']['CustomField7'] );
$stmt->bindParam(':CustomField8', $_SESSION['invoicedetail']['CustomField8'] );
$stmt->bindParam(':CustomField9', $_SESSION['invoicedetail']['CustomField9'] );
$stmt->bindParam(':CustomField10', $_SESSION['invoicedetail']['CustomField10'] );
$stmt->bindParam(':CustomField11', $_SESSION['invoicedetail']['CustomField11'] );
$stmt->bindParam(':CustomField12', $_SESSION['invoicedetail']['CustomField12'] );
$stmt->bindParam(':CustomField13', $_SESSION['invoicedetail']['CustomField13'] );
$stmt->bindParam(':CustomField14', $_SESSION['invoicedetail']['CustomField14'] );
$stmt->bindParam(':CustomField15', $_SESSION['invoicedetail']['CustomField15'] );
$stmt->bindParam(':IDKEY', $_SESSION['invoicedetail']['IDKEY'] );
//$stmt->bindParam(':GroupIDKEY', $_SESSION['invoicedetail']['GroupIDKEY'] );
$stmt->execute();
} catch(PDOException $e) {
    echo $e->getMessage();
}    
}

function quitaslashes_invoicedetail()
{
         $_SESSION['invoicedetail']['TxnLineID'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['TxnLineID']));
$_SESSION['invoicedetail']['ItemRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['ItemRef_ListID']));
$_SESSION['invoicedetail']['ItemRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['ItemRef_FullName']));
$_SESSION['invoicedetail']['Description'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['Description']));
$_SESSION['invoicedetail']['Quantity'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['Quantity']));
$_SESSION['invoicedetail']['UnitOfMeasure'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['UnitOfMeasure']));
$_SESSION['invoicedetail']['OverrideUOMSetRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['OverrideUOMSetRef_ListID']));
$_SESSION['invoicedetail']['OverrideUOMSetRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['OverrideUOMSetRef_FullName']));
$_SESSION['invoicedetail']['Rate'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['Rate']));
$_SESSION['invoicedetail']['RatePercent'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['RatePercent']));
$_SESSION['invoicedetail']['ClassRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['ClassRef_ListID']));
$_SESSION['invoicedetail']['ClassRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['ClassRef_FullName']));
$_SESSION['invoicedetail']['Amount'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['Amount']));
$_SESSION['invoicedetail']['InventorySiteRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['InventorySiteRef_ListID']));
$_SESSION['invoicedetail']['InventorySiteRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['InventorySiteRef_FullName']));
$_SESSION['invoicedetail']['InventorySiteLocationRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['InventorySiteLocationRef_ListID']));
$_SESSION['invoicedetail']['InventorySiteLocationRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['InventorySiteLocationRef_FullName']));
$_SESSION['invoicedetail']['SerialNumber'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['SerialNumber']));
$_SESSION['invoicedetail']['LotNumber'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['LotNumber']));
$_SESSION['invoicedetail']['ServiceDate'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['ServiceDate']));
$_SESSION['invoicedetail']['SalesTaxCodeRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['SalesTaxCodeRef_ListID']));
$_SESSION['invoicedetail']['SalesTaxCodeRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['SalesTaxCodeRef_FullName']));
$_SESSION['invoicedetail']['Other1'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['Other1']));
$_SESSION['invoicedetail']['Other2'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['Other2']));
$_SESSION['invoicedetail']['LinkedTxnID'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['LinkedTxnID']));
$_SESSION['invoicedetail']['LinkedTxnLineID'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['LinkedTxnLineID']));
$_SESSION['invoicedetail']['CustomField1'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['CustomField1']));
$_SESSION['invoicedetail']['CustomField2'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['CustomField2']));
$_SESSION['invoicedetail']['CustomField3'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['CustomField3']));
$_SESSION['invoicedetail']['CustomField4'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['CustomField4']));
$_SESSION['invoicedetail']['CustomField5'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['CustomField5']));
$_SESSION['invoicedetail']['CustomField6'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['CustomField6']));
$_SESSION['invoicedetail']['CustomField7'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['CustomField7']));
$_SESSION['invoicedetail']['CustomField8'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['CustomField8']));
$_SESSION['invoicedetail']['CustomField9'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['CustomField9']));
$_SESSION['invoicedetail']['CustomField10'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['CustomField10']));
$_SESSION['invoicedetail']['CustomField11'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['CustomField11']));
$_SESSION['invoicedetail']['CustomField12'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['CustomField12']));
$_SESSION['invoicedetail']['CustomField13'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['CustomField13']));
$_SESSION['invoicedetail']['CustomField14'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['CustomField14']));
$_SESSION['invoicedetail']['CustomField15'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['CustomField15']));
//$_SESSION['invoicedetail']['IDKEY'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['IDKEY']));
//$_SESSION['invoicedetail']['GroupIDKEY'] = htmlspecialchars(strip_tags($_SESSION['invoicedetail']['GroupIDKEY']));

 
    }
    


// **********************
// GETTER METHODS
// **********************


function getTxnLineID()
{
return $this->TxnLineID;
}

function getItemRef_ListID()
{
return $this->ItemRef_ListID;
}

function getItemRef_FullName()
{
return $this->ItemRef_FullName;
}

function getDescription()
{
return $this->Description;
}

function getQuantity()
{
return $this->Quantity;
}

function getUnitOfMeasure()
{
return $this->UnitOfMeasure;
}

function getOverrideUOMSetRef_ListID()
{
return $this->OverrideUOMSetRef_ListID;
}

function getOverrideUOMSetRef_FullName()
{
return $this->OverrideUOMSetRef_FullName;
}

function getRate()
{
return $this->Rate;
}

function getRatePercent()
{
return $this->RatePercent;
}

function getClassRef_ListID()
{
return $this->ClassRef_ListID;
}

function getClassRef_FullName()
{
return $this->ClassRef_FullName;
}

function getAmount()
{
return $this->Amount;
}

function getInventorySiteRef_ListID()
{
return $this->InventorySiteRef_ListID;
}

function getInventorySiteRef_FullName()
{
return $this->InventorySiteRef_FullName;
}

function getInventorySiteLocationRef_ListID()
{
return $this->InventorySiteLocationRef_ListID;
}

function getInventorySiteLocationRef_FullName()
{
return $this->InventorySiteLocationRef_FullName;
}

function getSerialNumber()
{
return $this->SerialNumber;
}

function getLotNumber()
{
return $this->LotNumber;
}

function getServiceDate()
{
return $this->ServiceDate;
}

function getSalesTaxCodeRef_ListID()
{
return $this->SalesTaxCodeRef_ListID;
}

function getSalesTaxCodeRef_FullName()
{
return $this->SalesTaxCodeRef_FullName;
}

function getOther1()
{
return $this->Other1;
}

function getOther2()
{
return $this->Other2;
}

function getLinkedTxnID()
{
return $this->LinkedTxnID;
}

function getLinkedTxnLineID()
{
return $this->LinkedTxnLineID;
}

function getCustomField1()
{
return $this->CustomField1;
}

function getCustomField2()
{
return $this->CustomField2;
}

function getCustomField3()
{
return $this->CustomField3;
}

function getCustomField4()
{
return $this->CustomField4;
}

function getCustomField5()
{
return $this->CustomField5;
}

function getCustomField6()
{
return $this->CustomField6;
}

function getCustomField7()
{
return $this->CustomField7;
}

function getCustomField8()
{
return $this->CustomField8;
}

function getCustomField9()
{
return $this->CustomField9;
}

function getCustomField10()
{
return $this->CustomField10;
}

function getCustomField11()
{
return $this->CustomField11;
}

function getCustomField12()
{
return $this->CustomField12;
}

function getCustomField13()
{
return $this->CustomField13;
}

function getCustomField14()
{
return $this->CustomField14;
}

function getCustomField15()
{
return $this->CustomField15;
}

function getIDKEY()
{
return $this->IDKEY;
}

function getGroupIDKEY()
{
return $this->GroupIDKEY;
}

// **********************
// SETTER METHODS
// **********************


function setTxnLineID($val)
{
$this->TxnLineID =  $val;
}

function setItemRef_ListID($val)
{
$this->ItemRef_ListID =  $val;
}

function setItemRef_FullName($val)
{
$this->ItemRef_FullName =  $val;
}

function setDescription($val)
{
$this->Description =  $val;
}

function setQuantity($val)
{
$this->Quantity =  $val;
}

function setUnitOfMeasure($val)
{
$this->UnitOfMeasure =  $val;
}

function setOverrideUOMSetRef_ListID($val)
{
$this->OverrideUOMSetRef_ListID =  $val;
}

function setOverrideUOMSetRef_FullName($val)
{
$this->OverrideUOMSetRef_FullName =  $val;
}

function setRate($val)
{
$this->Rate =  $val;
}

function setRatePercent($val)
{
$this->RatePercent =  $val;
}

function setClassRef_ListID($val)
{
$this->ClassRef_ListID =  $val;
}

function setClassRef_FullName($val)
{
$this->ClassRef_FullName =  $val;
}

function setAmount($val)
{
$this->Amount =  $val;
}

function setInventorySiteRef_ListID($val)
{
$this->InventorySiteRef_ListID =  $val;
}

function setInventorySiteRef_FullName($val)
{
$this->InventorySiteRef_FullName =  $val;
}

function setInventorySiteLocationRef_ListID($val)
{
$this->InventorySiteLocationRef_ListID =  $val;
}

function setInventorySiteLocationRef_FullName($val)
{
$this->InventorySiteLocationRef_FullName =  $val;
}

function setSerialNumber($val)
{
$this->SerialNumber =  $val;
}

function setLotNumber($val)
{
$this->LotNumber =  $val;
}

function setServiceDate($val)
{
$this->ServiceDate =  $val;
}

function setSalesTaxCodeRef_ListID($val)
{
$this->SalesTaxCodeRef_ListID =  $val;
}

function setSalesTaxCodeRef_FullName($val)
{
$this->SalesTaxCodeRef_FullName =  $val;
}

function setOther1($val)
{
$this->Other1 =  $val;
}

function setOther2($val)
{
$this->Other2 =  $val;
}

function setLinkedTxnID($val)
{
$this->LinkedTxnID =  $val;
}

function setLinkedTxnLineID($val)
{
$this->LinkedTxnLineID =  $val;
}

function setCustomField1($val)
{
$this->CustomField1 =  $val;
}

function setCustomField2($val)
{
$this->CustomField2 =  $val;
}

function setCustomField3($val)
{
$this->CustomField3 =  $val;
}

function setCustomField4($val)
{
$this->CustomField4 =  $val;
}

function setCustomField5($val)
{
$this->CustomField5 =  $val;
}

function setCustomField6($val)
{
$this->CustomField6 =  $val;
}

function setCustomField7($val)
{
$this->CustomField7 =  $val;
}

function setCustomField8($val)
{
$this->CustomField8 =  $val;
}

function setCustomField9($val)
{
$this->CustomField9 =  $val;
}

function setCustomField10($val)
{
$this->CustomField10 =  $val;
}

function setCustomField11($val)
{
$this->CustomField11 =  $val;
}

function setCustomField12($val)
{
$this->CustomField12 =  $val;
}

function setCustomField13($val)
{
$this->CustomField13 =  $val;
}

function setCustomField14($val)
{
$this->CustomField14 =  $val;
}

function setCustomField15($val)
{
$this->CustomField15 =  $val;
}

function setIDKEY($val)
{
$this->IDKEY =  $val;
}

function setGroupIDKEY($val)
{
$this->GroupIDKEY =  $val;
}

// **********************
// SELECT METHOD / LOAD
// **********************

function select_1($id)
{

$db = $this->db->aurora_connect();
$sql =  "SELECT * FROM invoicelinedetail WHERE TxnLineID = ?";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
    $stmt->bind_param("s", $id);
        $stmt->bind_result($db_TxnLineID, $db_ItemRef_ListID, $db_ItemRef_FullName, $db_Description, $db_Quantity, $db_UnitOfMeasure, $db_OverrideUOMSetRef_ListID, $db_OverrideUOMSetRef_FullName, $db_Rate, $db_RatePercent, $db_ClassRef_ListID, $db_ClassRef_FullName, $db_Amount, $db_InventorySiteRef_ListID, $db_InventorySiteRef_FullName, $db_InventorySiteLocationRef_ListID, $db_InventorySiteLocationRef_FullName, $db_SerialNumber, $db_LotNumber, $db_ServiceDate, $db_SalesTaxCodeRef_ListID, $db_SalesTaxCodeRef_FullName, $db_Other1, $db_Other2, $db_LinkedTxnID, $db_LinkedTxnLineID, $db_CustomField1, $db_CustomField2, $db_CustomField3, $db_CustomField4, $db_CustomField5, $db_CustomField6, $db_CustomField7, $db_CustomField8, $db_CustomField9, $db_CustomField10, $db_CustomField11, $db_CustomField12, $db_CustomField13, $db_CustomField14, $db_CustomField15, $db_IDKEY, $db_GroupIDKEY);
            $stmt->execute();
                if ($stmt->fetch()) {
                $this->TxnLineID = $db_TxnLineID;
$this->ItemRef_ListID = $db_ItemRef_ListID;
$this->ItemRef_FullName = $db_ItemRef_FullName;
$this->Description = $db_Description;
$this->Quantity = $db_Quantity;
$this->UnitOfMeasure = $db_UnitOfMeasure;
$this->OverrideUOMSetRef_ListID = $db_OverrideUOMSetRef_ListID;
$this->OverrideUOMSetRef_FullName = $db_OverrideUOMSetRef_FullName;
$this->Rate = $db_Rate;
$this->RatePercent = $db_RatePercent;
$this->ClassRef_ListID = $db_ClassRef_ListID;
$this->ClassRef_FullName = $db_ClassRef_FullName;
$this->Amount = $db_Amount;
$this->InventorySiteRef_ListID = $db_InventorySiteRef_ListID;
$this->InventorySiteRef_FullName = $db_InventorySiteRef_FullName;
$this->InventorySiteLocationRef_ListID = $db_InventorySiteLocationRef_ListID;
$this->InventorySiteLocationRef_FullName = $db_InventorySiteLocationRef_FullName;
$this->SerialNumber = $db_SerialNumber;
$this->LotNumber = $db_LotNumber;
$this->ServiceDate = $db_ServiceDate;
$this->SalesTaxCodeRef_ListID = $db_SalesTaxCodeRef_ListID;
$this->SalesTaxCodeRef_FullName = $db_SalesTaxCodeRef_FullName;
$this->Other1 = $db_Other1;
$this->Other2 = $db_Other2;
$this->LinkedTxnID = $db_LinkedTxnID;
$this->LinkedTxnLineID = $db_LinkedTxnLineID;
$this->CustomField1 = $db_CustomField1;
$this->CustomField2 = $db_CustomField2;
$this->CustomField3 = $db_CustomField3;
$this->CustomField4 = $db_CustomField4;
$this->CustomField5 = $db_CustomField5;
$this->CustomField6 = $db_CustomField6;
$this->CustomField7 = $db_CustomField7;
$this->CustomField8 = $db_CustomField8;
$this->CustomField9 = $db_CustomField9;
$this->CustomField10 = $db_CustomField10;
$this->CustomField11 = $db_CustomField11;
$this->CustomField12 = $db_CustomField12;
$this->CustomField13 = $db_CustomField13;
$this->CustomField14 = $db_CustomField14;
$this->CustomField15 = $db_CustomField15;
$this->IDKEY = $db_IDKEY;
$this->GroupIDKEY = $db_GroupIDKEY;


            }
$db->close();
}

// *******************************
// SELECT METHOD / FETCH LOOP
// *******************************
function buscaIgual_invoicedetail() {
    $estado = "ERR";
//    $this->db1 = conecta_PDO();
    $this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    try {
        $sql =  "SELECT * FROM invoicelinedetail WHERE TxnLineID = :clave ";
        $stmt = $this->db->prepare($sql);
        $stmt->bindParam(':clave', $_SESSION['invoicedetail']['TxnLineID']);
        $stmt->execute();
        if (!$stmt->fetch()) {
                $estado = "OK";
    
        }
} catch(PDOException $e) {
    echo $e->getMessage();
} 
    
return $estado;
}
function seleccionar_2($id)
{

$db = $this->db->aurora_connect();
$sql =  "SELECT * FROM invoicelinedetail WHERE TxnLineID = ?";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
    $stmt->bind_param("s", $id);
        $stmt->bind_result($db_TxnLineID, $db_ItemRef_ListID, $db_ItemRef_FullName, $db_Description, $db_Quantity, $db_UnitOfMeasure, $db_OverrideUOMSetRef_ListID, $db_OverrideUOMSetRef_FullName, $db_Rate, $db_RatePercent, $db_ClassRef_ListID, $db_ClassRef_FullName, $db_Amount, $db_InventorySiteRef_ListID, $db_InventorySiteRef_FullName, $db_InventorySiteLocationRef_ListID, $db_InventorySiteLocationRef_FullName, $db_SerialNumber, $db_LotNumber, $db_ServiceDate, $db_SalesTaxCodeRef_ListID, $db_SalesTaxCodeRef_FullName, $db_Other1, $db_Other2, $db_LinkedTxnID, $db_LinkedTxnLineID, $db_CustomField1, $db_CustomField2, $db_CustomField3, $db_CustomField4, $db_CustomField5, $db_CustomField6, $db_CustomField7, $db_CustomField8, $db_CustomField9, $db_CustomField10, $db_CustomField11, $db_CustomField12, $db_CustomField13, $db_CustomField14, $db_CustomField15, $db_IDKEY, $db_GroupIDKEY);
            $stmt->execute();
                while ($stmt->fetch()) {
                $this->TxnLineID = $db_TxnLineID;
$this->ItemRef_ListID = $db_ItemRef_ListID;
$this->ItemRef_FullName = $db_ItemRef_FullName;
$this->Description = $db_Description;
$this->Quantity = $db_Quantity;
$this->UnitOfMeasure = $db_UnitOfMeasure;
$this->OverrideUOMSetRef_ListID = $db_OverrideUOMSetRef_ListID;
$this->OverrideUOMSetRef_FullName = $db_OverrideUOMSetRef_FullName;
$this->Rate = $db_Rate;
$this->RatePercent = $db_RatePercent;
$this->ClassRef_ListID = $db_ClassRef_ListID;
$this->ClassRef_FullName = $db_ClassRef_FullName;
$this->Amount = $db_Amount;
$this->InventorySiteRef_ListID = $db_InventorySiteRef_ListID;
$this->InventorySiteRef_FullName = $db_InventorySiteRef_FullName;
$this->InventorySiteLocationRef_ListID = $db_InventorySiteLocationRef_ListID;
$this->InventorySiteLocationRef_FullName = $db_InventorySiteLocationRef_FullName;
$this->SerialNumber = $db_SerialNumber;
$this->LotNumber = $db_LotNumber;
$this->ServiceDate = $db_ServiceDate;
$this->SalesTaxCodeRef_ListID = $db_SalesTaxCodeRef_ListID;
$this->SalesTaxCodeRef_FullName = $db_SalesTaxCodeRef_FullName;
$this->Other1 = $db_Other1;
$this->Other2 = $db_Other2;
$this->LinkedTxnID = $db_LinkedTxnID;
$this->LinkedTxnLineID = $db_LinkedTxnLineID;
$this->CustomField1 = $db_CustomField1;
$this->CustomField2 = $db_CustomField2;
$this->CustomField3 = $db_CustomField3;
$this->CustomField4 = $db_CustomField4;
$this->CustomField5 = $db_CustomField5;
$this->CustomField6 = $db_CustomField6;
$this->CustomField7 = $db_CustomField7;
$this->CustomField8 = $db_CustomField8;
$this->CustomField9 = $db_CustomField9;
$this->CustomField10 = $db_CustomField10;
$this->CustomField11 = $db_CustomField11;
$this->CustomField12 = $db_CustomField12;
$this->CustomField13 = $db_CustomField13;
$this->CustomField14 = $db_CustomField14;
$this->CustomField15 = $db_CustomField15;
$this->IDKEY = $db_IDKEY;
$this->GroupIDKEY = $db_GroupIDKEY;


            }
$db->close();
}

// *******************************
// SELECT METHOD / FETCH LOOP
// *******************************

function recorrer_3($id)
{

$db = $this->db->aurora_connect();
$sql =  "SELECT * FROM invoicelinedetail WHERE TxnLineID = ?";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
    $stmt->bind_param("s", $id);
        $stmt->bind_result($db_TxnLineID, $db_ItemRef_ListID, $db_ItemRef_FullName, $db_Description, $db_Quantity, $db_UnitOfMeasure, $db_OverrideUOMSetRef_ListID, $db_OverrideUOMSetRef_FullName, $db_Rate, $db_RatePercent, $db_ClassRef_ListID, $db_ClassRef_FullName, $db_Amount, $db_InventorySiteRef_ListID, $db_InventorySiteRef_FullName, $db_InventorySiteLocationRef_ListID, $db_InventorySiteLocationRef_FullName, $db_SerialNumber, $db_LotNumber, $db_ServiceDate, $db_SalesTaxCodeRef_ListID, $db_SalesTaxCodeRef_FullName, $db_Other1, $db_Other2, $db_LinkedTxnID, $db_LinkedTxnLineID, $db_CustomField1, $db_CustomField2, $db_CustomField3, $db_CustomField4, $db_CustomField5, $db_CustomField6, $db_CustomField7, $db_CustomField8, $db_CustomField9, $db_CustomField10, $db_CustomField11, $db_CustomField12, $db_CustomField13, $db_CustomField14, $db_CustomField15, $db_IDKEY, $db_GroupIDKEY);
            $stmt->execute();
                if ($stmt->fetch()) {
                $_SESSION['invoicedetail']['TxnLineID'] = $this->getTxnLineID();
$_SESSION['invoicedetail']['ItemRef_ListID'] = $this->getItemRef_ListID();
$_SESSION['invoicedetail']['ItemRef_FullName'] = $this->getItemRef_FullName();
$_SESSION['invoicedetail']['Description'] = $this->getDescription();
$_SESSION['invoicedetail']['Quantity'] = $this->getQuantity();
$_SESSION['invoicedetail']['UnitOfMeasure'] = $this->getUnitOfMeasure();
$_SESSION['invoicedetail']['OverrideUOMSetRef_ListID'] = $this->getOverrideUOMSetRef_ListID();
$_SESSION['invoicedetail']['OverrideUOMSetRef_FullName'] = $this->getOverrideUOMSetRef_FullName();
$_SESSION['invoicedetail']['Rate'] = $this->getRate();
$_SESSION['invoicedetail']['RatePercent'] = $this->getRatePercent();
$_SESSION['invoicedetail']['ClassRef_ListID'] = $this->getClassRef_ListID();
$_SESSION['invoicedetail']['ClassRef_FullName'] = $this->getClassRef_FullName();
$_SESSION['invoicedetail']['Amount'] = $this->getAmount();
$_SESSION['invoicedetail']['InventorySiteRef_ListID'] = $this->getInventorySiteRef_ListID();
$_SESSION['invoicedetail']['InventorySiteRef_FullName'] = $this->getInventorySiteRef_FullName();
$_SESSION['invoicedetail']['InventorySiteLocationRef_ListID'] = $this->getInventorySiteLocationRef_ListID();
$_SESSION['invoicedetail']['InventorySiteLocationRef_FullName'] = $this->getInventorySiteLocationRef_FullName();
$_SESSION['invoicedetail']['SerialNumber'] = $this->getSerialNumber();
$_SESSION['invoicedetail']['LotNumber'] = $this->getLotNumber();
$_SESSION['invoicedetail']['ServiceDate'] = $this->getServiceDate();
$_SESSION['invoicedetail']['SalesTaxCodeRef_ListID'] = $this->getSalesTaxCodeRef_ListID();
$_SESSION['invoicedetail']['SalesTaxCodeRef_FullName'] = $this->getSalesTaxCodeRef_FullName();
$_SESSION['invoicedetail']['Other1'] = $this->getOther1();
$_SESSION['invoicedetail']['Other2'] = $this->getOther2();
$_SESSION['invoicedetail']['LinkedTxnID'] = $this->getLinkedTxnID();
$_SESSION['invoicedetail']['LinkedTxnLineID'] = $this->getLinkedTxnLineID();
$_SESSION['invoicedetail']['CustomField1'] = $this->getCustomField1();
$_SESSION['invoicedetail']['CustomField2'] = $this->getCustomField2();
$_SESSION['invoicedetail']['CustomField3'] = $this->getCustomField3();
$_SESSION['invoicedetail']['CustomField4'] = $this->getCustomField4();
$_SESSION['invoicedetail']['CustomField5'] = $this->getCustomField5();
$_SESSION['invoicedetail']['CustomField6'] = $this->getCustomField6();
$_SESSION['invoicedetail']['CustomField7'] = $this->getCustomField7();
$_SESSION['invoicedetail']['CustomField8'] = $this->getCustomField8();
$_SESSION['invoicedetail']['CustomField9'] = $this->getCustomField9();
$_SESSION['invoicedetail']['CustomField10'] = $this->getCustomField10();
$_SESSION['invoicedetail']['CustomField11'] = $this->getCustomField11();
$_SESSION['invoicedetail']['CustomField12'] = $this->getCustomField12();
$_SESSION['invoicedetail']['CustomField13'] = $this->getCustomField13();
$_SESSION['invoicedetail']['CustomField14'] = $this->getCustomField14();
$_SESSION['invoicedetail']['CustomField15'] = $this->getCustomField15();
$_SESSION['invoicedetail']['IDKEY'] = $this->getIDKEY();
$_SESSION['invoicedetail']['GroupIDKEY'] = $this->getGroupIDKEY();


            }
$db->close();
}

// *******************************
// UNSET METHOD / clean
// *******************************

function cleanSession_invoicedetail($jsonString)
{

                unset($_SESSION['invoicedetail']['TxnLineID']);
unset($_SESSION['invoicedetail']['ItemRef_ListID']);
unset($_SESSION['invoicedetail']['ItemRef_FullName']);
unset($_SESSION['invoicedetail']['Description']);
unset($_SESSION['invoicedetail']['Quantity']);
unset($_SESSION['invoicedetail']['UnitOfMeasure']);
unset($_SESSION['invoicedetail']['OverrideUOMSetRef_ListID']);
unset($_SESSION['invoicedetail']['OverrideUOMSetRef_FullName']);
unset($_SESSION['invoicedetail']['Rate']);
unset($_SESSION['invoicedetail']['RatePercent']);
unset($_SESSION['invoicedetail']['ClassRef_ListID']);
unset($_SESSION['invoicedetail']['ClassRef_FullName']);
unset($_SESSION['invoicedetail']['Amount']);
unset($_SESSION['invoicedetail']['InventorySiteRef_ListID']);
unset($_SESSION['invoicedetail']['InventorySiteRef_FullName']);
unset($_SESSION['invoicedetail']['InventorySiteLocationRef_ListID']);
unset($_SESSION['invoicedetail']['InventorySiteLocationRef_FullName']);
unset($_SESSION['invoicedetail']['SerialNumber']);
unset($_SESSION['invoicedetail']['LotNumber']);
unset($_SESSION['invoicedetail']['ServiceDate']);
unset($_SESSION['invoicedetail']['SalesTaxCodeRef_ListID']);
unset($_SESSION['invoicedetail']['SalesTaxCodeRef_FullName']);
unset($_SESSION['invoicedetail']['Other1']);
unset($_SESSION['invoicedetail']['Other2']);
unset($_SESSION['invoicedetail']['LinkedTxnID']);
unset($_SESSION['invoicedetail']['LinkedTxnLineID']);
unset($_SESSION['invoicedetail']['CustomField1']);
unset($_SESSION['invoicedetail']['CustomField2']);
unset($_SESSION['invoicedetail']['CustomField3']);
unset($_SESSION['invoicedetail']['CustomField4']);
unset($_SESSION['invoicedetail']['CustomField5']);
unset($_SESSION['invoicedetail']['CustomField6']);
unset($_SESSION['invoicedetail']['CustomField7']);
unset($_SESSION['invoicedetail']['CustomField8']);
unset($_SESSION['invoicedetail']['CustomField9']);
unset($_SESSION['invoicedetail']['CustomField10']);
unset($_SESSION['invoicedetail']['CustomField11']);
unset($_SESSION['invoicedetail']['CustomField12']);
unset($_SESSION['invoicedetail']['CustomField13']);
unset($_SESSION['invoicedetail']['CustomField14']);
unset($_SESSION['invoicedetail']['CustomField15']);
unset($_SESSION['invoicedetail']['IDKEY']);
unset($_SESSION['invoicedetail']['GroupIDKEY']);

}

// **********************
// DELETE
// **********************

function delete_4($id)
{
$db = $this->db->aurora_connect();
$sql = "DELETE FROM invoicelinedetail WHERE TxnLineID = ?";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
    $stmt->bind_param("s", $id);
        $stmt->execute();

$db->close();
}

// **********************
// INSERT
// **********************

function insert_5()
{
$this->TxnLineID = ""; // clear key for autoincrement
$db = $this->db->aurora_connect();
$sql = "INSERT INTO invoicelinedetail ( ItemRef_ListID,ItemRef_FullName,Description,Quantity,UnitOfMeasure,OverrideUOMSetRef_ListID,OverrideUOMSetRef_FullName,Rate,RatePercent,ClassRef_ListID,ClassRef_FullName,Amount,InventorySiteRef_ListID,InventorySiteRef_FullName,InventorySiteLocationRef_ListID,InventorySiteLocationRef_FullName,SerialNumber,LotNumber,ServiceDate,SalesTaxCodeRef_ListID,SalesTaxCodeRef_FullName,Other1,Other2,LinkedTxnID,LinkedTxnLineID,CustomField1,CustomField2,CustomField3,CustomField4,CustomField5,CustomField6,CustomField7,CustomField8,CustomField9,CustomField10,CustomField11,CustomField12,CustomField13,CustomField14,CustomField15,IDKEY,GroupIDKEY ) VALUES ( '$this->ItemRef_ListID','$this->ItemRef_FullName','$this->Description','$this->Quantity','$this->UnitOfMeasure','$this->OverrideUOMSetRef_ListID','$this->OverrideUOMSetRef_FullName','$this->Rate','$this->RatePercent','$this->ClassRef_ListID','$this->ClassRef_FullName','$this->Amount','$this->InventorySiteRef_ListID','$this->InventorySiteRef_FullName','$this->InventorySiteLocationRef_ListID','$this->InventorySiteLocationRef_FullName','$this->SerialNumber','$this->LotNumber','$this->ServiceDate','$this->SalesTaxCodeRef_ListID','$this->SalesTaxCodeRef_FullName','$this->Other1','$this->Other2','$this->LinkedTxnID','$this->LinkedTxnLineID','$this->CustomField1','$this->CustomField2','$this->CustomField3','$this->CustomField4','$this->CustomField5','$this->CustomField6','$this->CustomField7','$this->CustomField8','$this->CustomField9','$this->CustomField10','$this->CustomField11','$this->CustomField12','$this->CustomField13','$this->CustomField14','$this->CustomField15','$this->IDKEY','$this->GroupIDKEY' )";
$stmt = $db->prepare($sql) or die(mysqli_error($db));
$stmt->execute();

$db->close();
}

// **********************
// UPDATE
// **********************

function actualiza_invoicedetail($db)
{
    $estado = 'INIT';
	 $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            try {
	$sql = 'UPDATE invoicelinedetail SET ItemRef_ListID=:ItemRef_ListID, ItemRef_FullName=:ItemRef_FullName, Description=:Description, Quantity=:Quantity, UnitOfMeasure=:UnitOfMeasure, OverrideUOMSetRef_ListID=:OverrideUOMSetRef_ListID, OverrideUOMSetRef_FullName=:OverrideUOMSetRef_FullName, Rate=:Rate, RatePercent=:RatePercent, ClassRef_ListID=:ClassRef_ListID, ClassRef_FullName=:ClassRef_FullName, Amount=:Amount, InventorySiteRef_ListID=:InventorySiteRef_ListID, InventorySiteRef_FullName=:InventorySiteRef_FullName, InventorySiteLocationRef_ListID=:InventorySiteLocationRef_ListID, InventorySiteLocationRef_FullName=:InventorySiteLocationRef_FullName, SerialNumber=:SerialNumber, LotNumber=:LotNumber, ServiceDate=:ServiceDate, SalesTaxCodeRef_ListID=:SalesTaxCodeRef_ListID, SalesTaxCodeRef_FullName=:SalesTaxCodeRef_FullName, Other1=:Other1, Other2=:Other2, LinkedTxnID=:LinkedTxnID, LinkedTxnLineID=:LinkedTxnLineID, CustomField1=:CustomField1, CustomField2=:CustomField2, CustomField3=:CustomField3, CustomField4=:CustomField4, CustomField5=:CustomField5, CustomField6=:CustomField6, CustomField7=:CustomField7, CustomField8=:CustomField8, CustomField9=:CustomField9, CustomField10=:CustomField10, CustomField11=:CustomField11, CustomField12=:CustomField12, CustomField13=:CustomField13, CustomField14=:CustomField14, CustomField15=:CustomField15, IDKEY=:IDKEY WHERE TxnLineID = :clave;'; 
	$stmt = $db->prepare($sql);
	 
	$stmt->bindParam(':ItemRef_ListID', $_SESSION['invoicedetail']['ItemRef_ListID'] );
	$stmt->bindParam(':ItemRef_FullName', $_SESSION['invoicedetail']['ItemRef_FullName'] );
	$stmt->bindParam(':Description', $_SESSION['invoicedetail']['Description'] );
	$stmt->bindParam(':Quantity', $_SESSION['invoicedetail']['Quantity'] );
	$stmt->bindParam(':UnitOfMeasure', $_SESSION['invoicedetail']['UnitOfMeasure'] );
	$stmt->bindParam(':OverrideUOMSetRef_ListID', $_SESSION['invoicedetail']['OverrideUOMSetRef_ListID'] );
	$stmt->bindParam(':OverrideUOMSetRef_FullName', $_SESSION['invoicedetail']['OverrideUOMSetRef_FullName'] );
	$stmt->bindParam(':Rate', $_SESSION['invoicedetail']['Rate'] );
	$stmt->bindParam(':RatePercent', $_SESSION['invoicedetail']['RatePercent'] );
	$stmt->bindParam(':ClassRef_ListID', $_SESSION['invoicedetail']['ClassRef_ListID'] );
	$stmt->bindParam(':ClassRef_FullName', $_SESSION['invoicedetail']['ClassRef_FullName'] );
	$stmt->bindParam(':Amount', $_SESSION['invoicedetail']['Amount'] );
	$stmt->bindParam(':InventorySiteRef_ListID', $_SESSION['invoicedetail']['InventorySiteRef_ListID'] );
	$stmt->bindParam(':InventorySiteRef_FullName', $_SESSION['invoicedetail']['InventorySiteRef_FullName'] );
	$stmt->bindParam(':InventorySiteLocationRef_ListID', $_SESSION['invoicedetail']['InventorySiteLocationRef_ListID'] );
	$stmt->bindParam(':InventorySiteLocationRef_FullName', $_SESSION['invoicedetail']['InventorySiteLocationRef_FullName'] );
	$stmt->bindParam(':SerialNumber', $_SESSION['invoicedetail']['SerialNumber'] );
	$stmt->bindParam(':LotNumber', $_SESSION['invoicedetail']['LotNumber'] );
	$stmt->bindParam(':ServiceDate', $_SESSION['invoicedetail']['ServiceDate'] );
	$stmt->bindParam(':SalesTaxCodeRef_ListID', $_SESSION['invoicedetail']['SalesTaxCodeRef_ListID'] );
	$stmt->bindParam(':SalesTaxCodeRef_FullName', $_SESSION['invoicedetail']['SalesTaxCodeRef_FullName'] );
	$stmt->bindParam(':Other1', $_SESSION['invoicedetail']['Other1'] );
	$stmt->bindParam(':Other2', $_SESSION['invoicedetail']['Other2'] );
	$stmt->bindParam(':LinkedTxnID', $_SESSION['invoicedetail']['LinkedTxnID'] );
	$stmt->bindParam(':LinkedTxnLineID', $_SESSION['invoicedetail']['LinkedTxnLineID'] );
	$stmt->bindParam(':CustomField1', $_SESSION['invoicedetail']['CustomField1'] );
	$stmt->bindParam(':CustomField2', $_SESSION['invoicedetail']['CustomField2'] );
	$stmt->bindParam(':CustomField3', $_SESSION['invoicedetail']['CustomField3'] );
	$stmt->bindParam(':CustomField4', $_SESSION['invoicedetail']['CustomField4'] );
	$stmt->bindParam(':CustomField5', $_SESSION['invoicedetail']['CustomField5'] );
	$stmt->bindParam(':CustomField6', $_SESSION['invoicedetail']['CustomField6'] );
	$stmt->bindParam(':CustomField7', $_SESSION['invoicedetail']['CustomField7'] );
	$stmt->bindParam(':CustomField8', $_SESSION['invoicedetail']['CustomField8'] );
	$stmt->bindParam(':CustomField9', $_SESSION['invoicedetail']['CustomField9'] );
	$stmt->bindParam(':CustomField10', $_SESSION['invoicedetail']['CustomField10'] );
	$stmt->bindParam(':CustomField11', $_SESSION['invoicedetail']['CustomField11'] );
	$stmt->bindParam(':CustomField12', $_SESSION['invoicedetail']['CustomField12'] );
	$stmt->bindParam(':CustomField13', $_SESSION['invoicedetail']['CustomField13'] );
	$stmt->bindParam(':CustomField14', $_SESSION['invoicedetail']['CustomField14'] );
	$stmt->bindParam(':CustomField15', $_SESSION['invoicedetail']['CustomField15'] );
	$stmt->bindParam(':IDKEY', $_SESSION['invoicedetail']['IDKEY'] );
	$stmt->bindParam(':GroupIDKEY', $_SESSION['invoicedetail']['GroupIDKEY'] );
	$stmt->bindParam(':clave', $_SESSION['invoice']['TxnID']);
	$stmt->execute();
     } catch(PDOException $e) {
     	
}
     }
     
     function update_invoicedetail()
{

    $estado = "ERR";
    $this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    try {
        $sql = " UPDATE invoicelinedetail SET  ItemRef_ListID = '$this->ItemRef_ListID',ItemRef_FullName = '$this->ItemRef_FullName',Description = '$this->Description',Quantity = '$this->Quantity',UnitOfMeasure = '$this->UnitOfMeasure',OverrideUOMSetRef_ListID = '$this->OverrideUOMSetRef_ListID',OverrideUOMSetRef_FullName = '$this->OverrideUOMSetRef_FullName',Rate = '$this->Rate',RatePercent = '$this->RatePercent',ClassRef_ListID = '$this->ClassRef_ListID',ClassRef_FullName = '$this->ClassRef_FullName',Amount = '$this->Amount',InventorySiteRef_ListID = '$this->InventorySiteRef_ListID',InventorySiteRef_FullName = '$this->InventorySiteRef_FullName',InventorySiteLocationRef_ListID = '$this->InventorySiteLocationRef_ListID',InventorySiteLocationRef_FullName = '$this->InventorySiteLocationRef_FullName',SerialNumber = '$this->SerialNumber',LotNumber = '$this->LotNumber',ServiceDate = '$this->ServiceDate',SalesTaxCodeRef_ListID = '$this->SalesTaxCodeRef_ListID',SalesTaxCodeRef_FullName = '$this->SalesTaxCodeRef_FullName',Other1 = '$this->Other1',Other2 = '$this->Other2',LinkedTxnID = '$this->LinkedTxnID',LinkedTxnLineID = '$this->LinkedTxnLineID',CustomField1 = '$this->CustomField1',CustomField2 = '$this->CustomField2',CustomField3 = '$this->CustomField3',CustomField4 = '$this->CustomField4',CustomField5 = '$this->CustomField5',CustomField6 = '$this->CustomField6',CustomField7 = '$this->CustomField7',CustomField8 = '$this->CustomField8',CustomField9 = '$this->CustomField9',CustomField10 = '$this->CustomField10',CustomField11 = '$this->CustomField11',CustomField12 = '$this->CustomField12',CustomField13 = '$this->CustomField13',CustomField14 = '$this->CustomField14',CustomField15 = '$this->CustomField15',IDKEY = '$this->IDKEY',GroupIDKEY = '$this->GroupIDKEY' WHERE TxnLineID = :clave ";

        $stmt = $this->db->prepare($sql);
        $stmt->bindParam(":clave", $_SESSION['invoicedetail']['TxnLineID']);
        $stmt->execute();

     } catch(PDOException $e) {

     }

}

}
?>
<!-- end of generated class -->
