<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        mycustomer
* GENERATION DATE:  03.11.2017
* CLASS FILE:       C:\wamp64\www\genera_clase/generated_classes/class.mycustomer.php
* FOR MYSQL TABLE:  my_customer_table
* FOR MYSQL DB:     auroraec_aurora
* -------------------------------------------------------
* CODE GENERATED BY:
* MY PHP-MYSQL-CLASS GENERATOR
* from: >> www.voegeli.li >> (download for free!)
* modify: >> www.aurora-ec.net >> (download for free!)
* -------------------------------------------------------
*
*/
include_once("class.aurora.php");
// **********************
// CLASS DECLARATION
// **********************

class mycustomer
{ // class : begin


// **********************
// ATTRIBUTE DECLARATION
// **********************


public $id;   // (normal Attribute)
public $timecreated;   // (normal Attribute)
public $timemodified;   // (normal Attribute)
public $name;   // (normal Attribute)
public $fullname;   // (normal Attribute)
public $fname;   // (normal Attribute)
public $lname;   // (normal Attribute)
public $salutation;   // (normal Attribute)
public $address;   // (normal Attribute)
public $city;   // (normal Attribute)
public $state;   // (normal Attribute)
public $zipcode;   // (normal Attribute)
public $country;   // (normal Attribute)
public $email;   // (normal Attribute)
public $quickbooks_listid;   // (normal Attribute)
public $quickbooks_editsequence;   // (normal Attribute)
public $quickbooks_errnum;   // (normal Attribute)
public $quickbooks_errmsg;   // (normal Attribute)
public $sales_rep_ref_listid;   // (normal Attribute)
public $sales_rep_ref_fullname;   // (normal Attribute)
public $sales_tax_code_ref_listid;   // (normal Attribute)
public $sales_tax_code_ref_fullname;   // (normal Attribute)
public $tax_code_ref_listid;   // (normal Attribute)
public $tax_code_ref_fullname;   // (normal Attribute)
public $item_sales_tax_ref_listid;   // (normal Attribute)
public $item_sales_tax_ref_fullname;   // (normal Attribute)

var $db; // Instance of class database
var $estado; 


// **********************
// CONSTRUCTOR METHOD
// **********************

function __construct()
{

$this->db = conecta_SYNC();
}

function __destruct()
{


}
public function initialize($entity = null, $options = array())
    {
     $timecreated= new Date("timecreated");
$timecreated->setLabel("timecreated");
$timecreated->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($timecreated);

$timemodified= new Date("timemodified");
$timemodified->setLabel("timemodified");
$timemodified->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($timemodified);

$name= new Text("name");
$name->setLabel("name");
$name->setFilters(array('striptags', 'strig'));
$name->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($name);

$fullname= new Text("fullname");
$fullname->setLabel("fullname");
$fullname->setFilters(array('striptags', 'strig'));
$fullname->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($fullname);

$fname= new Text("fname");
$fname->setLabel("fname");
$fname->setFilters(array('striptags', 'strig'));
$fname->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($fname);

$lname= new Text("lname");
$lname->setLabel("lname");
$lname->setFilters(array('striptags', 'strig'));
$lname->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($lname);

$salutation= new Text("salutation");
$salutation->setLabel("salutation");
$salutation->setFilters(array('striptags', 'strig'));
$salutation->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($salutation);

$address= new Text("address");
$address->setLabel("address");
$address->setFilters(array('striptags', 'strig'));
$address->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($address);

$city= new Text("city");
$city->setLabel("city");
$city->setFilters(array('striptags', 'strig'));
$city->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($city);

$state= new Text("state");
$state->setLabel("state");
$state->setFilters(array('striptags', 'strig'));
$state->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($state);

$zipcode= new Text("zipcode");
$zipcode->setLabel("zipcode");
$zipcode->setFilters(array('striptags', 'strig'));
$zipcode->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($zipcode);

$country= new Text("country");
$country->setLabel("country");
$country->setFilters(array('striptags', 'strig'));
$country->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($country);

$email= new Text("email");
$email->setLabel("email");
$email->setFilters(array('striptags', 'strig'));
$email->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($email);

$quickbooks_listid= new Text("quickbooks_listid");
$quickbooks_listid->setLabel("quickbooks_listid");
$quickbooks_listid->setFilters(array('striptags', 'strig'));
$quickbooks_listid->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($quickbooks_listid);

$quickbooks_editsequence= new Text("quickbooks_editsequence");
$quickbooks_editsequence->setLabel("quickbooks_editsequence");
$quickbooks_editsequence->setFilters(array('striptags', 'strig'));
$quickbooks_editsequence->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($quickbooks_editsequence);

$quickbooks_errnum= new Text("quickbooks_errnum");
$quickbooks_errnum->setLabel("quickbooks_errnum");
$quickbooks_errnum->setFilters(array('striptags', 'strig'));
$quickbooks_errnum->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($quickbooks_errnum);

$quickbooks_errmsg= new Text("quickbooks_errmsg");
$quickbooks_errmsg->setLabel("quickbooks_errmsg");
$quickbooks_errmsg->setFilters(array('striptags', 'strig'));
$quickbooks_errmsg->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($quickbooks_errmsg);

$sales_rep_ref_listid= new Text("sales_rep_ref_listid");
$sales_rep_ref_listid->setLabel("sales_rep_ref_listid");
$sales_rep_ref_listid->setFilters(array('striptags', 'strig'));
$sales_rep_ref_listid->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($sales_rep_ref_listid);

$sales_rep_ref_fullname= new Text("sales_rep_ref_fullname");
$sales_rep_ref_fullname->setLabel("sales_rep_ref_fullname");
$sales_rep_ref_fullname->setFilters(array('striptags', 'strig'));
$sales_rep_ref_fullname->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($sales_rep_ref_fullname);

$sales_tax_code_ref_listid= new Text("sales_tax_code_ref_listid");
$sales_tax_code_ref_listid->setLabel("sales_tax_code_ref_listid");
$sales_tax_code_ref_listid->setFilters(array('striptags', 'strig'));
$sales_tax_code_ref_listid->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($sales_tax_code_ref_listid);

$sales_tax_code_ref_fullname= new Text("sales_tax_code_ref_fullname");
$sales_tax_code_ref_fullname->setLabel("sales_tax_code_ref_fullname");
$sales_tax_code_ref_fullname->setFilters(array('striptags', 'strig'));
$sales_tax_code_ref_fullname->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($sales_tax_code_ref_fullname);

$tax_code_ref_listid= new Text("tax_code_ref_listid");
$tax_code_ref_listid->setLabel("tax_code_ref_listid");
$tax_code_ref_listid->setFilters(array('striptags', 'strig'));
$tax_code_ref_listid->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($tax_code_ref_listid);

$tax_code_ref_fullname= new Text("tax_code_ref_fullname");
$tax_code_ref_fullname->setLabel("tax_code_ref_fullname");
$tax_code_ref_fullname->setFilters(array('striptags', 'strig'));
$tax_code_ref_fullname->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($tax_code_ref_fullname);

$item_sales_tax_ref_listid= new Text("item_sales_tax_ref_listid");
$item_sales_tax_ref_listid->setLabel("item_sales_tax_ref_listid");
$item_sales_tax_ref_listid->setFilters(array('striptags', 'strig'));
$item_sales_tax_ref_listid->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($item_sales_tax_ref_listid);

$item_sales_tax_ref_fullname= new Text("item_sales_tax_ref_fullname");
$item_sales_tax_ref_fullname->setLabel("item_sales_tax_ref_fullname");
$item_sales_tax_ref_fullname->setFilters(array('striptags', 'strig'));
$item_sales_tax_ref_fullname->addValidators(array(
new PresenceOf(array(
'message'=> 'Mensaje de validacion'
))
));
$this->add($item_sales_tax_ref_fullname);


    }
    
function genJson_mycustomer($jsonString)
{
$_SESSION['mycustomer']['id'] = $jsonString->id;
$_SESSION['mycustomer']['timecreated'] = $jsonString->timecreated;
$_SESSION['mycustomer']['timemodified'] = $jsonString->timemodified;
$_SESSION['mycustomer']['name'] = $jsonString->name;
$_SESSION['mycustomer']['fullname'] = $jsonString->fullname;
$_SESSION['mycustomer']['fname'] = $jsonString->fname;
$_SESSION['mycustomer']['lname'] = $jsonString->lname;
$_SESSION['mycustomer']['salutation'] = $jsonString->salutation;
$_SESSION['mycustomer']['address'] = $jsonString->address;
$_SESSION['mycustomer']['city'] = $jsonString->city;
$_SESSION['mycustomer']['state'] = $jsonString->state;
$_SESSION['mycustomer']['zipcode'] = $jsonString->zipcode;
$_SESSION['mycustomer']['country'] = $jsonString->country;
$_SESSION['mycustomer']['email'] = $jsonString->email;
$_SESSION['mycustomer']['quickbooks_listid'] = $jsonString->quickbooks_listid;
$_SESSION['mycustomer']['quickbooks_editsequence'] = $jsonString->quickbooks_editsequence;
$_SESSION['mycustomer']['quickbooks_errnum'] = $jsonString->quickbooks_errnum;
$_SESSION['mycustomer']['quickbooks_errmsg'] = $jsonString->quickbooks_errmsg;
$_SESSION['mycustomer']['sales_rep_ref_listid'] = $jsonString->sales_rep_ref_listid;
$_SESSION['mycustomer']['sales_rep_ref_fullname'] = $jsonString->sales_rep_ref_fullname;
$_SESSION['mycustomer']['sales_tax_code_ref_listid'] = $jsonString->sales_tax_code_ref_listid;
$_SESSION['mycustomer']['sales_tax_code_ref_fullname'] = $jsonString->sales_tax_code_ref_fullname;
$_SESSION['mycustomer']['tax_code_ref_listid'] = $jsonString->tax_code_ref_listid;
$_SESSION['mycustomer']['tax_code_ref_fullname'] = $jsonString->tax_code_ref_fullname;
$_SESSION['mycustomer']['item_sales_tax_ref_listid'] = $jsonString->item_sales_tax_ref_listid;
$_SESSION['mycustomer']['item_sales_tax_ref_fullname'] = $jsonString->item_sales_tax_ref_fullname;

}

function genInsert_mycustomer()
{
$this->setid($_SESSION['mycustomer']['id']);
$this->settimecreated($_SESSION['mycustomer']['timecreated']);
$this->settimemodified($_SESSION['mycustomer']['timemodified']);
$this->setname($_SESSION['mycustomer']['name']);
$this->setfullname($_SESSION['mycustomer']['fullname']);
$this->setfname($_SESSION['mycustomer']['fname']);
$this->setlname($_SESSION['mycustomer']['lname']);
$this->setsalutation($_SESSION['mycustomer']['salutation']);
$this->setaddress($_SESSION['mycustomer']['address']);
$this->setcity($_SESSION['mycustomer']['city']);
$this->setstate($_SESSION['mycustomer']['state']);
$this->setzipcode($_SESSION['mycustomer']['zipcode']);
$this->setcountry($_SESSION['mycustomer']['country']);
$this->setemail($_SESSION['mycustomer']['email']);
$this->setquickbooks_listid($_SESSION['mycustomer']['quickbooks_listid']);
$this->setquickbooks_editsequence($_SESSION['mycustomer']['quickbooks_editsequence']);
$this->setquickbooks_errnum($_SESSION['mycustomer']['quickbooks_errnum']);
$this->setquickbooks_errmsg($_SESSION['mycustomer']['quickbooks_errmsg']);
$this->setsales_rep_ref_listid($_SESSION['mycustomer']['sales_rep_ref_listid']);
$this->setsales_rep_ref_fullname($_SESSION['mycustomer']['sales_rep_ref_fullname']);
$this->setsales_tax_code_ref_listid($_SESSION['mycustomer']['sales_tax_code_ref_listid']);
$this->setsales_tax_code_ref_fullname($_SESSION['mycustomer']['sales_tax_code_ref_fullname']);
$this->settax_code_ref_listid($_SESSION['mycustomer']['tax_code_ref_listid']);
$this->settax_code_ref_fullname($_SESSION['mycustomer']['tax_code_ref_fullname']);
$this->setitem_sales_tax_ref_listid($_SESSION['mycustomer']['item_sales_tax_ref_listid']);
$this->setitem_sales_tax_ref_fullname($_SESSION['mycustomer']['item_sales_tax_ref_fullname']);

}

function genLimpia_mycustomer()
{
$_SESSION['mycustomer']['ListID'] = ' ';
$_SESSION['mycustomer']['TimeCreated'] = ' ';
$_SESSION['mycustomer']['TimeModified'] = ' ';
$_SESSION['mycustomer']['EditSequence'] = ' ';
$_SESSION['mycustomer']['Name'] = ' ';
$_SESSION['mycustomer']['FullName'] = ' ';
$_SESSION['mycustomer']['IsActive'] = ' ';
$_SESSION['mycustomer']['ClassRef_ListID'] = ' ';
$_SESSION['mycustomer']['ClassRef_FullName'] = ' ';
$_SESSION['mycustomer']['ParentRef_ListID'] = ' ';
$_SESSION['mycustomer']['ParentRef_FullName'] = ' ';
$_SESSION['mycustomer']['Sublevel'] = ' ';
$_SESSION['mycustomer']['CompanyName'] = ' ';
$_SESSION['mycustomer']['Salutation'] = ' ';
$_SESSION['mycustomer']['FirstName'] = ' ';
$_SESSION['mycustomer']['MiddleName'] = ' ';
$_SESSION['mycustomer']['LastName'] = ' ';
$_SESSION['mycustomer']['Suffix'] = ' ';
$_SESSION['mycustomer']['BillAddress_Addr1'] = ' ';
$_SESSION['mycustomer']['BillAddress_Addr2'] = ' ';
$_SESSION['mycustomer']['BillAddress_Addr3'] = ' ';
$_SESSION['mycustomer']['BillAddress_Addr4'] = ' ';
$_SESSION['mycustomer']['BillAddress_Addr5'] = ' ';
$_SESSION['mycustomer']['BillAddress_City'] = ' ';
$_SESSION['mycustomer']['BillAddress_State'] = ' ';
$_SESSION['mycustomer']['BillAddress_PostalCode'] = ' ';
$_SESSION['mycustomer']['BillAddress_Country'] = ' ';
$_SESSION['mycustomer']['BillAddress_Note'] = ' ';
$_SESSION['mycustomer']['ShipAddress_Addr1'] = ' ';
$_SESSION['mycustomer']['ShipAddress_Addr2'] = ' ';
$_SESSION['mycustomer']['ShipAddress_Addr3'] = ' ';
$_SESSION['mycustomer']['ShipAddress_Addr4'] = ' ';
$_SESSION['mycustomer']['ShipAddress_Addr5'] = ' ';
$_SESSION['mycustomer']['ShipAddress_City'] = ' ';
$_SESSION['mycustomer']['ShipAddress_State'] = ' ';
$_SESSION['mycustomer']['ShipAddress_PostalCode'] = ' ';
$_SESSION['mycustomer']['ShipAddress_Country'] = ' ';
$_SESSION['mycustomer']['ShipAddress_Note'] = ' ';
$_SESSION['mycustomer']['PrintAs'] = ' ';
$_SESSION['mycustomer']['Phone'] = ' ';
$_SESSION['mycustomer']['Mobile'] = ' ';
$_SESSION['mycustomer']['Pager'] = ' ';
$_SESSION['mycustomer']['AltPhone'] = ' ';
$_SESSION['mycustomer']['Fax'] = ' ';
$_SESSION['mycustomer']['Email'] = ' ';
$_SESSION['mycustomer']['Cc'] = ' ';
$_SESSION['mycustomer']['Contact'] = ' ';
$_SESSION['mycustomer']['AltContact'] = ' ';
$_SESSION['mycustomer']['CustomerTypeRef_ListID'] = ' ';
$_SESSION['mycustomer']['CustomerTypeRef_FullName'] = ' ';
$_SESSION['mycustomer']['TermsRef_ListID'] = ' ';
$_SESSION['mycustomer']['TermsRef_FullName'] = ' ';
$_SESSION['mycustomer']['SalesRepRef_ListID'] = ' ';
$_SESSION['mycustomer']['SalesRepRef_FullName'] = ' ';
$_SESSION['mycustomer']['Balance'] = ' ';
$_SESSION['mycustomer']['TotalBalance'] = ' ';
$_SESSION['mycustomer']['SalesTaxCodeRef_ListID'] = ' ';
$_SESSION['mycustomer']['SalesTaxCodeRef_FullName'] = ' ';
$_SESSION['mycustomer']['ItemSalesTaxRef_ListID'] = ' ';
$_SESSION['mycustomer']['ItemSalesTaxRef_FullName'] = ' ';
$_SESSION['mycustomer']['SalesTaxCountry'] = ' ';
$_SESSION['mycustomer']['ResaleNumber'] = ' ';
$_SESSION['mycustomer']['AccountNumber'] = ' ';
$_SESSION['mycustomer']['CreditLimit'] = ' ';
$_SESSION['mycustomer']['PreferredPaymentMethodRef_ListID'] = ' ';
$_SESSION['mycustomer']['PreferredPaymentMethodRef_FullName'] = ' ';
$_SESSION['mycustomer']['CreditCardNumber'] = ' ';
$_SESSION['mycustomer']['ExpirationMonth'] = ' ';
$_SESSION['mycustomer']['ExpirationYear'] = ' ';
$_SESSION['mycustomer']['NameOnCard'] = ' ';
$_SESSION['mycustomer']['CreditCardAddress'] = ' ';
$_SESSION['mycustomer']['CreditCardPostalCode'] = ' ';
$_SESSION['mycustomer']['JobStatus'] = ' ';
$_SESSION['mycustomer']['JobStartDate'] = ' ';
$_SESSION['mycustomer']['JobProjectedEndDate'] = ' ';
$_SESSION['mycustomer']['JobEndDate'] = ' ';
$_SESSION['mycustomer']['JobDesc'] = ' ';
$_SESSION['mycustomer']['JobTypeRef_ListID'] = ' ';
$_SESSION['mycustomer']['JobTypeRef_FullName'] = ' ';
$_SESSION['mycustomer']['Notes'] = ' ';
$_SESSION['mycustomer']['PriceLevelRef_ListID'] = ' ';
$_SESSION['mycustomer']['PriceLevelRef_FullName'] = ' ';
$_SESSION['mycustomer']['TaxRegistrationNumber'] = ' ';
$_SESSION['mycustomer']['CurrencyRef_ListID'] = ' ';
$_SESSION['mycustomer']['CurrencyRef_FullName'] = ' ';
$_SESSION['mycustomer']['IsStatementWithParent'] = ' ';
$_SESSION['mycustomer']['PreferredDeliveryMethod'] = ' ';

}

function gentraverse_mycustomer($node)
{
$node->getElementsByTagName('ListID')->item(0) == NULL ? $_SESSION['mycustomer']['ListID'] = ' ' : $_SESSION['mycustomer']['ListID'] = $node->getElementsByTagName('ListID')->item(0)->nodeValue;
$node->getElementsByTagName('TimeCreated')->item(0) == NULL ? $_SESSION['mycustomer']['TimeCreated'] = '2010-08-10' : $_SESSION['mycustomer']['TimeCreated'] = $node->getElementsByTagName('TimeCreated')->item(0)->nodeValue;
$node->getElementsByTagName('TimeModified')->item(0) == NULL ? $_SESSION['mycustomer']['TimeModified'] = '2010-08-10' : $_SESSION['mycustomer']['TimeModified'] = $node->getElementsByTagName('TimeModified')->item(0)->nodeValue;
$node->getElementsByTagName('EditSequence')->item(0) == NULL ? $_SESSION['mycustomer']['EditSequence'] = 0 : $_SESSION['mycustomer']['EditSequence'] = $node->getElementsByTagName('EditSequence')->item(0)->nodeValue;
$node->getElementsByTagName('Name')->item(0) == NULL ? $_SESSION['mycustomer']['Name'] = ' ' : $_SESSION['mycustomer']['Name'] = $node->getElementsByTagName('Name')->item(0)->nodeValue;
$node->getElementsByTagName('FullName')->item(0) == NULL ? $_SESSION['mycustomer']['FullName'] = ' ' : $_SESSION['mycustomer']['FullName'] = $node->getElementsByTagName('FullName')->item(0)->nodeValue;
$node->getElementsByTagName('IsActive')->item(0) == NULL ? $_SESSION['mycustomer']['IsActive'] = ' ' : $_SESSION['mycustomer']['IsActive'] = $node->getElementsByTagName('IsActive')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(1) == NULL ? $_SESSION['mycustomer']['ClassRef_ListID'] = ' ' : $_SESSION['mycustomer']['ClassRef_ListID'] = $node->getElementsByTagName('ListID')->item(1)->nodeValue;
$node->getElementsByTagName('FullName')->item(0) == NULL ? $_SESSION['mycustomer']['ClassRef_FullName'] = ' ' : $_SESSION['mycustomer']['ClassRef_FullName'] = $node->getElementsByTagName('FullName')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(2) == NULL ? $_SESSION['mycustomer']['ParentRef_ListID'] = ' ' : $_SESSION['mycustomer']['ParentRef_ListID'] = $node->getElementsByTagName('ListID')->item(2)->nodeValue;
$node->getElementsByTagName('FullName')->item(0) == NULL ? $_SESSION['mycustomer']['ParentRef_FullName'] = ' ' : $_SESSION['mycustomer']['ParentRef_FullName'] = $node->getElementsByTagName('FullName')->item(0)->nodeValue;
$node->getElementsByTagName('Sublevel')->item(0) == NULL ? $_SESSION['mycustomer']['Sublevel'] = 0 : $_SESSION['mycustomer']['Sublevel'] = $node->getElementsByTagName('Sublevel')->item(0)->nodeValue;
$node->getElementsByTagName('CompanyName')->item(0) == NULL ? $_SESSION['mycustomer']['CompanyName'] = ' ' : $_SESSION['mycustomer']['CompanyName'] = $node->getElementsByTagName('CompanyName')->item(0)->nodeValue;
$node->getElementsByTagName('Salutation')->item(0) == NULL ? $_SESSION['mycustomer']['Salutation'] = ' ' : $_SESSION['mycustomer']['Salutation'] = $node->getElementsByTagName('Salutation')->item(0)->nodeValue;
$node->getElementsByTagName('FirstName')->item(0) == NULL ? $_SESSION['mycustomer']['FirstName'] = ' ' : $_SESSION['mycustomer']['FirstName'] = $node->getElementsByTagName('FirstName')->item(0)->nodeValue;
$node->getElementsByTagName('MiddleName')->item(0) == NULL ? $_SESSION['mycustomer']['MiddleName'] = ' ' : $_SESSION['mycustomer']['MiddleName'] = $node->getElementsByTagName('MiddleName')->item(0)->nodeValue;
$node->getElementsByTagName('LastName')->item(0) == NULL ? $_SESSION['mycustomer']['LastName'] = ' ' : $_SESSION['mycustomer']['LastName'] = $node->getElementsByTagName('LastName')->item(0)->nodeValue;
$node->getElementsByTagName('Suffix')->item(0) == NULL ? $_SESSION['mycustomer']['Suffix'] = ' ' : $_SESSION['mycustomer']['Suffix'] = $node->getElementsByTagName('Suffix')->item(0)->nodeValue;
$node->getElementsByTagName('Addr1')->item(0) == NULL ? $_SESSION['mycustomer']['BillAddress_Addr1'] = ' ' : $_SESSION['mycustomer']['BillAddress_Addr1'] = $node->getElementsByTagName('Addr1')->item(0)->nodeValue;
$node->getElementsByTagName('Addr2')->item(0) == NULL ? $_SESSION['mycustomer']['BillAddress_Addr2'] = ' ' : $_SESSION['mycustomer']['BillAddress_Addr2'] = $node->getElementsByTagName('Addr2')->item(0)->nodeValue;
$node->getElementsByTagName('Addr3')->item(0) == NULL ? $_SESSION['mycustomer']['BillAddress_Addr3'] = ' ' : $_SESSION['mycustomer']['BillAddress_Addr3'] = $node->getElementsByTagName('Addr3')->item(0)->nodeValue;
$node->getElementsByTagName('Addr4')->item(0) == NULL ? $_SESSION['mycustomer']['BillAddress_Addr4'] = ' ' : $_SESSION['mycustomer']['BillAddress_Addr4'] = $node->getElementsByTagName('Addr4')->item(0)->nodeValue;
$node->getElementsByTagName('Addr5')->item(0) == NULL ? $_SESSION['mycustomer']['BillAddress_Addr5'] = ' ' : $_SESSION['mycustomer']['BillAddress_Addr5'] = $node->getElementsByTagName('Addr5')->item(0)->nodeValue;
$node->getElementsByTagName('City')->item(0) == NULL ? $_SESSION['mycustomer']['BillAddress_City'] = ' ' : $_SESSION['mycustomer']['BillAddress_City'] = $node->getElementsByTagName('City')->item(0)->nodeValue;
$node->getElementsByTagName('State')->item(0) == NULL ? $_SESSION['mycustomer']['BillAddress_State'] = ' ' : $_SESSION['mycustomer']['BillAddress_State'] = $node->getElementsByTagName('State')->item(0)->nodeValue;
$node->getElementsByTagName('PostalCode')->item(0) == NULL ? $_SESSION['mycustomer']['BillAddress_PostalCode'] = ' ' : $_SESSION['mycustomer']['BillAddress_PostalCode'] = $node->getElementsByTagName('PostalCode')->item(0)->nodeValue;
$node->getElementsByTagName('Country')->item(0) == NULL ? $_SESSION['mycustomer']['BillAddress_Country'] = ' ' : $_SESSION['mycustomer']['BillAddress_Country'] = $node->getElementsByTagName('Country')->item(0)->nodeValue;
$node->getElementsByTagName('Note')->item(0) == NULL ? $_SESSION['mycustomer']['BillAddress_Note'] = ' ' : $_SESSION['mycustomer']['BillAddress_Note'] = $node->getElementsByTagName('Note')->item(0)->nodeValue;
$node->getElementsByTagName('Addr1')->item(0) == NULL ? $_SESSION['mycustomer']['ShipAddress_Addr1'] = ' ' : $_SESSION['mycustomer']['ShipAddress_Addr1'] = $node->getElementsByTagName('Addr1')->item(0)->nodeValue;
$node->getElementsByTagName('Addr2')->item(0) == NULL ? $_SESSION['mycustomer']['ShipAddress_Addr2'] = ' ' : $_SESSION['mycustomer']['ShipAddress_Addr2'] = $node->getElementsByTagName('Addr2')->item(0)->nodeValue;
$node->getElementsByTagName('Addr3')->item(0) == NULL ? $_SESSION['mycustomer']['ShipAddress_Addr3'] = ' ' : $_SESSION['mycustomer']['ShipAddress_Addr3'] = $node->getElementsByTagName('Addr3')->item(0)->nodeValue;
$node->getElementsByTagName('Addr4')->item(0) == NULL ? $_SESSION['mycustomer']['ShipAddress_Addr4'] = ' ' : $_SESSION['mycustomer']['ShipAddress_Addr4'] = $node->getElementsByTagName('Addr4')->item(0)->nodeValue;
$node->getElementsByTagName('Addr5')->item(0) == NULL ? $_SESSION['mycustomer']['ShipAddress_Addr5'] = ' ' : $_SESSION['mycustomer']['ShipAddress_Addr5'] = $node->getElementsByTagName('Addr5')->item(0)->nodeValue;
$node->getElementsByTagName('City')->item(0) == NULL ? $_SESSION['mycustomer']['ShipAddress_City'] = ' ' : $_SESSION['mycustomer']['ShipAddress_City'] = $node->getElementsByTagName('City')->item(0)->nodeValue;
$node->getElementsByTagName('State')->item(0) == NULL ? $_SESSION['mycustomer']['ShipAddress_State'] = ' ' : $_SESSION['mycustomer']['ShipAddress_State'] = $node->getElementsByTagName('State')->item(0)->nodeValue;
$node->getElementsByTagName('PostalCode')->item(0) == NULL ? $_SESSION['mycustomer']['ShipAddress_PostalCode'] = ' ' : $_SESSION['mycustomer']['ShipAddress_PostalCode'] = $node->getElementsByTagName('PostalCode')->item(0)->nodeValue;
$node->getElementsByTagName('Country')->item(0) == NULL ? $_SESSION['mycustomer']['ShipAddress_Country'] = ' ' : $_SESSION['mycustomer']['ShipAddress_Country'] = $node->getElementsByTagName('Country')->item(0)->nodeValue;
$node->getElementsByTagName('Note')->item(0) == NULL ? $_SESSION['mycustomer']['ShipAddress_Note'] = ' ' : $_SESSION['mycustomer']['ShipAddress_Note'] = $node->getElementsByTagName('Note')->item(0)->nodeValue;
$node->getElementsByTagName('PrintAs')->item(0) == NULL ? $_SESSION['mycustomer']['PrintAs'] = ' ' : $_SESSION['mycustomer']['PrintAs'] = $node->getElementsByTagName('PrintAs')->item(0)->nodeValue;
$node->getElementsByTagName('Phone')->item(0) == NULL ? $_SESSION['mycustomer']['Phone'] = ' ' : $_SESSION['mycustomer']['Phone'] = $node->getElementsByTagName('Phone')->item(0)->nodeValue;
$node->getElementsByTagName('Mobile')->item(0) == NULL ? $_SESSION['mycustomer']['Mobile'] = ' ' : $_SESSION['mycustomer']['Mobile'] = $node->getElementsByTagName('Mobile')->item(0)->nodeValue;
$node->getElementsByTagName('Pager')->item(0) == NULL ? $_SESSION['mycustomer']['Pager'] = ' ' : $_SESSION['mycustomer']['Pager'] = $node->getElementsByTagName('Pager')->item(0)->nodeValue;
$node->getElementsByTagName('AltPhone')->item(0) == NULL ? $_SESSION['mycustomer']['AltPhone'] = ' ' : $_SESSION['mycustomer']['AltPhone'] = $node->getElementsByTagName('AltPhone')->item(0)->nodeValue;
$node->getElementsByTagName('Fax')->item(0) == NULL ? $_SESSION['mycustomer']['Fax'] = ' ' : $_SESSION['mycustomer']['Fax'] = $node->getElementsByTagName('Fax')->item(0)->nodeValue;
$node->getElementsByTagName('Email')->item(0) == NULL ? $_SESSION['mycustomer']['Email'] = ' ' : $_SESSION['mycustomer']['Email'] = $node->getElementsByTagName('Email')->item(0)->nodeValue;
$node->getElementsByTagName('Cc')->item(0) == NULL ? $_SESSION['mycustomer']['Cc'] = ' ' : $_SESSION['mycustomer']['Cc'] = $node->getElementsByTagName('Cc')->item(0)->nodeValue;
$node->getElementsByTagName('Contact')->item(0) == NULL ? $_SESSION['mycustomer']['Contact'] = ' ' : $_SESSION['mycustomer']['Contact'] = $node->getElementsByTagName('Contact')->item(0)->nodeValue;
$node->getElementsByTagName('AltContact')->item(0) == NULL ? $_SESSION['mycustomer']['AltContact'] = ' ' : $_SESSION['mycustomer']['AltContact'] = $node->getElementsByTagName('AltContact')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(3) == NULL ? $_SESSION['mycustomer']['CustomerTypeRef_ListID'] = ' ' : $_SESSION['mycustomer']['CustomerTypeRef_ListID'] = $node->getElementsByTagName('ListID')->item(3)->nodeValue;
$node->getElementsByTagName('FullName')->item(0) == NULL ? $_SESSION['mycustomer']['CustomerTypeRef_FullName'] = ' ' : $_SESSION['mycustomer']['CustomerTypeRef_FullName'] = $node->getElementsByTagName('FullName')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(4) == NULL ? $_SESSION['mycustomer']['TermsRef_ListID'] = ' ' : $_SESSION['mycustomer']['TermsRef_ListID'] = $node->getElementsByTagName('ListID')->item(4)->nodeValue;
$node->getElementsByTagName('FullName')->item(0) == NULL ? $_SESSION['mycustomer']['TermsRef_FullName'] = ' ' : $_SESSION['mycustomer']['TermsRef_FullName'] = $node->getElementsByTagName('FullName')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(5) == NULL ? $_SESSION['mycustomer']['SalesRepRef_ListID'] = ' ' : $_SESSION['mycustomer']['SalesRepRef_ListID'] = $node->getElementsByTagName('ListID')->item(5)->nodeValue;
$node->getElementsByTagName('FullName')->item(0) == NULL ? $_SESSION['mycustomer']['SalesRepRef_FullName'] = ' ' : $_SESSION['mycustomer']['SalesRepRef_FullName'] = $node->getElementsByTagName('FullName')->item(0)->nodeValue;
$node->getElementsByTagName('Balance')->item(0) == NULL ? $_SESSION['mycustomer']['Balance'] = 0 : $_SESSION['mycustomer']['Balance'] = $node->getElementsByTagName('Balance')->item(0)->nodeValue;
$node->getElementsByTagName('TotalBalance')->item(0) == NULL ? $_SESSION['mycustomer']['TotalBalance'] = 0 : $_SESSION['mycustomer']['TotalBalance'] = $node->getElementsByTagName('TotalBalance')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(6) == NULL ? $_SESSION['mycustomer']['SalesTaxCodeRef_ListID'] = ' ' : $_SESSION['mycustomer']['SalesTaxCodeRef_ListID'] = $node->getElementsByTagName('ListID')->item(6)->nodeValue;
$node->getElementsByTagName('FullName')->item(0) == NULL ? $_SESSION['mycustomer']['SalesTaxCodeRef_FullName'] = ' ' : $_SESSION['mycustomer']['SalesTaxCodeRef_FullName'] = $node->getElementsByTagName('FullName')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(7) == NULL ? $_SESSION['mycustomer']['ItemSalesTaxRef_ListID'] = ' ' : $_SESSION['mycustomer']['ItemSalesTaxRef_ListID'] = $node->getElementsByTagName('ListID')->item(7)->nodeValue;
$node->getElementsByTagName('FullName')->item(0) == NULL ? $_SESSION['mycustomer']['ItemSalesTaxRef_FullName'] = ' ' : $_SESSION['mycustomer']['ItemSalesTaxRef_FullName'] = $node->getElementsByTagName('FullName')->item(0)->nodeValue;
$node->getElementsByTagName('SalesTaxCountry')->item(0) == NULL ? $_SESSION['mycustomer']['SalesTaxCountry'] = ' ' : $_SESSION['mycustomer']['SalesTaxCountry'] = $node->getElementsByTagName('SalesTaxCountry')->item(0)->nodeValue;
$node->getElementsByTagName('ResaleNumber')->item(0) == NULL ? $_SESSION['mycustomer']['ResaleNumber'] = ' ' : $_SESSION['mycustomer']['ResaleNumber'] = $node->getElementsByTagName('ResaleNumber')->item(0)->nodeValue;
$node->getElementsByTagName('AccountNumber')->item(0) == NULL ? $_SESSION['mycustomer']['AccountNumber'] = ' ' : $_SESSION['mycustomer']['AccountNumber'] = $node->getElementsByTagName('AccountNumber')->item(0)->nodeValue;
$node->getElementsByTagName('CreditLimit')->item(0) == NULL ? $_SESSION['mycustomer']['CreditLimit'] = 0 : $_SESSION['mycustomer']['CreditLimit'] = $node->getElementsByTagName('CreditLimit')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(8) == NULL ? $_SESSION['mycustomer']['PreferredPaymentMethodRef_ListID'] = ' ' : $_SESSION['mycustomer']['PreferredPaymentMethodRef_ListID'] = $node->getElementsByTagName('ListID')->item(8)->nodeValue;
$node->getElementsByTagName('FullName')->item(0) == NULL ? $_SESSION['mycustomer']['PreferredPaymentMethodRef_FullName'] = ' ' : $_SESSION['mycustomer']['PreferredPaymentMethodRef_FullName'] = $node->getElementsByTagName('FullName')->item(0)->nodeValue;
$node->getElementsByTagName('CreditCardNumber')->item(0) == NULL ? $_SESSION['mycustomer']['CreditCardNumber'] = ' ' : $_SESSION['mycustomer']['CreditCardNumber'] = $node->getElementsByTagName('CreditCardNumber')->item(0)->nodeValue;
$node->getElementsByTagName('ExpirationMonth')->item(0) == NULL ? $_SESSION['mycustomer']['ExpirationMonth'] = 0 : $_SESSION['mycustomer']['ExpirationMonth'] = $node->getElementsByTagName('ExpirationMonth')->item(0)->nodeValue;
$node->getElementsByTagName('ExpirationYear')->item(0) == NULL ? $_SESSION['mycustomer']['ExpirationYear'] = 0 : $_SESSION['mycustomer']['ExpirationYear'] = $node->getElementsByTagName('ExpirationYear')->item(0)->nodeValue;
$node->getElementsByTagName('NameOnCard')->item(0) == NULL ? $_SESSION['mycustomer']['NameOnCard'] = ' ' : $_SESSION['mycustomer']['NameOnCard'] = $node->getElementsByTagName('NameOnCard')->item(0)->nodeValue;
$node->getElementsByTagName('CreditCardAddress')->item(0) == NULL ? $_SESSION['mycustomer']['CreditCardAddress'] = ' ' : $_SESSION['mycustomer']['CreditCardAddress'] = $node->getElementsByTagName('CreditCardAddress')->item(0)->nodeValue;
$node->getElementsByTagName('CreditCardPostalCode')->item(0) == NULL ? $_SESSION['mycustomer']['CreditCardPostalCode'] = ' ' : $_SESSION['mycustomer']['CreditCardPostalCode'] = $node->getElementsByTagName('CreditCardPostalCode')->item(0)->nodeValue;
$node->getElementsByTagName('JobStatus')->item(0) == NULL ? $_SESSION['mycustomer']['JobStatus'] = ' ' : $_SESSION['mycustomer']['JobStatus'] = $node->getElementsByTagName('JobStatus')->item(0)->nodeValue;
$node->getElementsByTagName('JobStartDate')->item(0) == NULL ? $_SESSION['mycustomer']['JobStartDate'] = '2010-08-10' : $_SESSION['mycustomer']['JobStartDate'] = $node->getElementsByTagName('JobStartDate')->item(0)->nodeValue;
$node->getElementsByTagName('JobProjectedEndDate')->item(0) == NULL ? $_SESSION['mycustomer']['JobProjectedEndDate'] = '2010-08-10' : $_SESSION['mycustomer']['JobProjectedEndDate'] = $node->getElementsByTagName('JobProjectedEndDate')->item(0)->nodeValue;
$node->getElementsByTagName('JobEndDate')->item(0) == NULL ? $_SESSION['mycustomer']['JobEndDate'] = '2010-08-10' : $_SESSION['mycustomer']['JobEndDate'] = $node->getElementsByTagName('JobEndDate')->item(0)->nodeValue;
$node->getElementsByTagName('JobDesc')->item(0) == NULL ? $_SESSION['mycustomer']['JobDesc'] = ' ' : $_SESSION['mycustomer']['JobDesc'] = $node->getElementsByTagName('JobDesc')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(9) == NULL ? $_SESSION['mycustomer']['JobTypeRef_ListID'] = ' ' : $_SESSION['mycustomer']['JobTypeRef_ListID'] = $node->getElementsByTagName('ListID')->item(9)->nodeValue;
$node->getElementsByTagName('FullName')->item(0) == NULL ? $_SESSION['mycustomer']['JobTypeRef_FullName'] = ' ' : $_SESSION['mycustomer']['JobTypeRef_FullName'] = $node->getElementsByTagName('FullName')->item(0)->nodeValue;
$node->getElementsByTagName('Notes')->item(0) == NULL ? $_SESSION['mycustomer']['Notes'] = ' ' : $_SESSION['mycustomer']['Notes'] = $node->getElementsByTagName('Notes')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(10) == NULL ? $_SESSION['mycustomer']['PriceLevelRef_ListID'] = ' ' : $_SESSION['mycustomer']['PriceLevelRef_ListID'] = $node->getElementsByTagName('ListID')->item(10)->nodeValue;
$node->getElementsByTagName('FullName')->item(0) == NULL ? $_SESSION['mycustomer']['PriceLevelRef_FullName'] = ' ' : $_SESSION['mycustomer']['PriceLevelRef_FullName'] = $node->getElementsByTagName('FullName')->item(0)->nodeValue;
$node->getElementsByTagName('TaxRegistrationNumber')->item(0) == NULL ? $_SESSION['mycustomer']['TaxRegistrationNumber'] = ' ' : $_SESSION['mycustomer']['TaxRegistrationNumber'] = $node->getElementsByTagName('TaxRegistrationNumber')->item(0)->nodeValue;
$node->getElementsByTagName('ListID')->item(11) == NULL ? $_SESSION['mycustomer']['CurrencyRef_ListID'] = ' ' : $_SESSION['mycustomer']['CurrencyRef_ListID'] = $node->getElementsByTagName('ListID')->item(11)->nodeValue;
$node->getElementsByTagName('FullName')->item(0) == NULL ? $_SESSION['mycustomer']['CurrencyRef_FullName'] = ' ' : $_SESSION['mycustomer']['CurrencyRef_FullName'] = $node->getElementsByTagName('FullName')->item(0)->nodeValue;
$node->getElementsByTagName('IsStatementWithParent')->item(0) == NULL ? $_SESSION['mycustomer']['IsStatementWithParent'] = ' ' : $_SESSION['mycustomer']['IsStatementWithParent'] = $node->getElementsByTagName('IsStatementWithParent')->item(0)->nodeValue;
$node->getElementsByTagName('PreferredDeliveryMethod')->item(0) == NULL ? $_SESSION['mycustomer']['PreferredDeliveryMethod'] = ' ' : $_SESSION['mycustomer']['PreferredDeliveryMethod'] = $node->getElementsByTagName('PreferredDeliveryMethod')->item(0)->nodeValue;

}

function adiciona_mycustomer()
{
        $this->estado = 'ERR';
	$this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        try {
        $sql = 'INSERT INTO my_customer_table (  timecreated, timemodified, name, fullname, fname, lname, salutation, address, city, state, zipcode, country, email, quickbooks_listid, quickbooks_editsequence, quickbooks_errnum, quickbooks_errmsg, sales_rep_ref_listid, sales_rep_ref_fullname, sales_tax_code_ref_listid, sales_tax_code_ref_fullname, tax_code_ref_listid, tax_code_ref_fullname, item_sales_tax_ref_listid, item_sales_tax_ref_fullname) VALUES ( :timecreated, :timemodified, :name, :fullname, :fname, :lname, :salutation, :address, :city, :state, :zipcode, :country, :email, :quickbooks_listid, :quickbooks_editsequence, :quickbooks_errnum, :quickbooks_errmsg, :sales_rep_ref_listid, :sales_rep_ref_fullname, :sales_tax_code_ref_listid, :sales_tax_code_ref_fullname, :tax_code_ref_listid, :tax_code_ref_fullname, :item_sales_tax_ref_listid, :item_sales_tax_ref_fullname)';
	$stmt = $this->db->prepare($sql);
	$stmt->bindParam(':timecreated', $_SESSION['mycustomer']['TimeCreated'] );
	$stmt->bindParam(':timemodified', $_SESSION['mycustomer']['TimeModified'] );
	$stmt->bindParam(':name', $_SESSION['mycustomer']['Name'] );
	$stmt->bindParam(':fullname', $_SESSION['mycustomer']['FullName'] );
	$stmt->bindParam(':fname', $_SESSION['mycustomer']['FirstName'] );
	$stmt->bindParam(':lname', $_SESSION['mycustomer']['LastName'] );
	$stmt->bindParam(':salutation', $_SESSION['mycustomer']['Salutation'] );
	$stmt->bindParam(':address', $_SESSION['mycustomer']['BillAddress_Addr1'] );
	$stmt->bindParam(':city', $_SESSION['mycustomer']['BillAddress_City'] );
	$stmt->bindParam(':state', $_SESSION['mycustomer']['BillAddress_State'] );
	$stmt->bindParam(':zipcode', $_SESSION['mycustomer']['BillAddress_PostalCode'] );
	$stmt->bindParam(':country', $_SESSION['mycustomer']['BillAddress_Country'] );
	$stmt->bindParam(':email', $_SESSION['mycustomer']['Email'] );
	$stmt->bindParam(':quickbooks_listid', $_SESSION['mycustomer']['ListID'] );
	$stmt->bindParam(':quickbooks_editsequence', $_SESSION['mycustomer']['EditSequence'] );
	$stmt->bindParam(':quickbooks_errnum', $_SESSION['mycustomer']['TermsRef_ListID'] );
	$stmt->bindParam(':quickbooks_errmsg', $_SESSION['mycustomer']['TermsRef_FullName'] );
	$stmt->bindParam(':sales_rep_ref_listid', $_SESSION['mycustomer']['SalesRepRef_ListID'] );
	$stmt->bindParam(':sales_rep_ref_fullname', $_SESSION['mycustomer']['SalesRepRef_FullName'] );
	$stmt->bindParam(':sales_tax_code_ref_listid', $_SESSION['mycustomer']['SalesTaxCodeRef_ListID'] );
	$stmt->bindParam(':sales_tax_code_ref_fullname', $_SESSION['mycustomer']['SalesTaxCodeRef_FullName'] );
	$stmt->bindParam(':tax_code_ref_listid', $_SESSION['mycustomer']['SalesTaxCodeRef_ListID'] );
	$stmt->bindParam(':tax_code_ref_fullname', $_SESSION['mycustomer']['SalesTaxCodeRef_FullName'] );
	$stmt->bindParam(':item_sales_tax_ref_listid', $_SESSION['mycustomer']['ItemSalesTaxRef_ListID'] );
	$stmt->bindParam(':item_sales_tax_ref_fullname', $_SESSION['mycustomer']['ItemSalesTaxRef_FullName'] );
	$stmt->execute();
        } catch(PDOException $e) {
            echo $e->getMessage();
        }    
}

function quitaslashes_mycustomer()
{

          $_SESSION['mycustomer']['ListID'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ListID']));
$_SESSION['mycustomer']['TimeCreated'] = date("Y-m-d H:m:s", strtotime($_SESSION['mycustomer']['TimeCreated']));
$_SESSION['mycustomer']['TimeModified'] = date("Y-m-d H:m:s", strtotime($_SESSION['mycustomer']['TimeCreated']));
$_SESSION['mycustomer']['EditSequence'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['EditSequence']));
$_SESSION['mycustomer']['Name'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['Name']));
$_SESSION['mycustomer']['FullName'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['FullName']));
$_SESSION['mycustomer']['IsActive'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['IsActive']));
$_SESSION['mycustomer']['ClassRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ClassRef_ListID']));
$_SESSION['mycustomer']['ClassRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ClassRef_FullName']));
$_SESSION['mycustomer']['ParentRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ParentRef_ListID']));
$_SESSION['mycustomer']['ParentRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ParentRef_FullName']));
$_SESSION['mycustomer']['Sublevel'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['Sublevel']));
$_SESSION['mycustomer']['CompanyName'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['CompanyName']));
$_SESSION['mycustomer']['Salutation'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['Salutation']));
$_SESSION['mycustomer']['FirstName'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['FirstName']));
$_SESSION['mycustomer']['MiddleName'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['MiddleName']));
$_SESSION['mycustomer']['LastName'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['LastName']));
$_SESSION['mycustomer']['Suffix'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['Suffix']));
$_SESSION['mycustomer']['BillAddress_Addr1'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['BillAddress_Addr1']));
$_SESSION['mycustomer']['BillAddress_Addr2'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['BillAddress_Addr2']));
$_SESSION['mycustomer']['BillAddress_Addr3'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['BillAddress_Addr3']));
$_SESSION['mycustomer']['BillAddress_Addr4'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['BillAddress_Addr4']));
$_SESSION['mycustomer']['BillAddress_Addr5'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['BillAddress_Addr5']));
$_SESSION['mycustomer']['BillAddress_City'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['BillAddress_City']));
$_SESSION['mycustomer']['BillAddress_State'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['BillAddress_State']));
$_SESSION['mycustomer']['BillAddress_PostalCode'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['BillAddress_PostalCode']));
$_SESSION['mycustomer']['BillAddress_Country'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['BillAddress_Country']));
$_SESSION['mycustomer']['BillAddress_Note'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['BillAddress_Note']));
$_SESSION['mycustomer']['ShipAddress_Addr1'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ShipAddress_Addr1']));
$_SESSION['mycustomer']['ShipAddress_Addr2'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ShipAddress_Addr2']));
$_SESSION['mycustomer']['ShipAddress_Addr3'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ShipAddress_Addr3']));
$_SESSION['mycustomer']['ShipAddress_Addr4'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ShipAddress_Addr4']));
$_SESSION['mycustomer']['ShipAddress_Addr5'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ShipAddress_Addr5']));
$_SESSION['mycustomer']['ShipAddress_City'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ShipAddress_City']));
$_SESSION['mycustomer']['ShipAddress_State'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ShipAddress_State']));
$_SESSION['mycustomer']['ShipAddress_PostalCode'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ShipAddress_PostalCode']));
$_SESSION['mycustomer']['ShipAddress_Country'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ShipAddress_Country']));
$_SESSION['mycustomer']['ShipAddress_Note'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ShipAddress_Note']));
$_SESSION['mycustomer']['PrintAs'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['PrintAs']));
$_SESSION['mycustomer']['Phone'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['Phone']));
$_SESSION['mycustomer']['Mobile'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['Mobile']));
$_SESSION['mycustomer']['Pager'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['Pager']));
$_SESSION['mycustomer']['AltPhone'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['AltPhone']));
$_SESSION['mycustomer']['Fax'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['Fax']));
$_SESSION['mycustomer']['Email'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['Email']));
$_SESSION['mycustomer']['Cc'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['Cc']));
$_SESSION['mycustomer']['Contact'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['Contact']));
$_SESSION['mycustomer']['AltContact'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['AltContact']));
$_SESSION['mycustomer']['CustomerTypeRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['CustomerTypeRef_ListID']));
$_SESSION['mycustomer']['CustomerTypeRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['CustomerTypeRef_FullName']));
$_SESSION['mycustomer']['TermsRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['TermsRef_ListID']));
$_SESSION['mycustomer']['TermsRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['TermsRef_FullName']));
$_SESSION['mycustomer']['SalesRepRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['SalesRepRef_ListID']));
$_SESSION['mycustomer']['SalesRepRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['SalesRepRef_FullName']));
$_SESSION['mycustomer']['Balance'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['Balance']));
$_SESSION['mycustomer']['TotalBalance'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['TotalBalance']));
$_SESSION['mycustomer']['SalesTaxCodeRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['SalesTaxCodeRef_ListID']));
$_SESSION['mycustomer']['SalesTaxCodeRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['SalesTaxCodeRef_FullName']));
$_SESSION['mycustomer']['ItemSalesTaxRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ItemSalesTaxRef_ListID']));
$_SESSION['mycustomer']['ItemSalesTaxRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ItemSalesTaxRef_FullName']));
$_SESSION['mycustomer']['SalesTaxCountry'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['SalesTaxCountry']));
$_SESSION['mycustomer']['ResaleNumber'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ResaleNumber']));
$_SESSION['mycustomer']['AccountNumber'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['AccountNumber']));
$_SESSION['mycustomer']['CreditLimit'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['CreditLimit']));
$_SESSION['mycustomer']['PreferredPaymentMethodRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['PreferredPaymentMethodRef_ListID']));
$_SESSION['mycustomer']['PreferredPaymentMethodRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['PreferredPaymentMethodRef_FullName']));
$_SESSION['mycustomer']['CreditCardNumber'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['CreditCardNumber']));
$_SESSION['mycustomer']['ExpirationMonth'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ExpirationMonth']));
$_SESSION['mycustomer']['ExpirationYear'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['ExpirationYear']));
$_SESSION['mycustomer']['NameOnCard'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['NameOnCard']));
$_SESSION['mycustomer']['CreditCardAddress'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['CreditCardAddress']));
$_SESSION['mycustomer']['CreditCardPostalCode'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['CreditCardPostalCode']));
$_SESSION['mycustomer']['JobStatus'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['JobStatus']));
$_SESSION['mycustomer']['JobStartDate'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['JobStartDate']));
$_SESSION['mycustomer']['JobProjectedEndDate'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['JobProjectedEndDate']));
$_SESSION['mycustomer']['JobEndDate'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['JobEndDate']));
$_SESSION['mycustomer']['JobDesc'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['JobDesc']));
$_SESSION['mycustomer']['JobTypeRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['JobTypeRef_ListID']));
$_SESSION['mycustomer']['JobTypeRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['JobTypeRef_FullName']));
$_SESSION['mycustomer']['Notes'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['Notes']));
$_SESSION['mycustomer']['PriceLevelRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['PriceLevelRef_ListID']));
$_SESSION['mycustomer']['PriceLevelRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['PriceLevelRef_FullName']));
$_SESSION['mycustomer']['TaxRegistrationNumber'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['TaxRegistrationNumber']));
$_SESSION['mycustomer']['CurrencyRef_ListID'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['CurrencyRef_ListID']));
$_SESSION['mycustomer']['CurrencyRef_FullName'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['CurrencyRef_FullName']));
$_SESSION['mycustomer']['IsStatementWithParent'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['IsStatementWithParent']));
$_SESSION['mycustomer']['PreferredDeliveryMethod'] = htmlspecialchars(strip_tags($_SESSION['mycustomer']['PreferredDeliveryMethod']));

    }
    


// **********************
// GETTER METHODS
// **********************


function getid()
{
return $this->id;
}

function gettimecreated()
{
return $this->timecreated;
}

function gettimemodified()
{
return $this->timemodified;
}

function getname()
{
return $this->name;
}

function getfullname()
{
return $this->fullname;
}

function getfname()
{
return $this->fname;
}

function getlname()
{
return $this->lname;
}

function getsalutation()
{
return $this->salutation;
}

function getaddress()
{
return $this->address;
}

function getcity()
{
return $this->city;
}

function getstate()
{
return $this->state;
}

function getzipcode()
{
return $this->zipcode;
}

function getcountry()
{
return $this->country;
}

function getemail()
{
return $this->email;
}

function getquickbooks_listid()
{
return $this->quickbooks_listid;
}

function getquickbooks_editsequence()
{
return $this->quickbooks_editsequence;
}

function getquickbooks_errnum()
{
return $this->quickbooks_errnum;
}

function getquickbooks_errmsg()
{
return $this->quickbooks_errmsg;
}

function getsales_rep_ref_listid()
{
return $this->sales_rep_ref_listid;
}

function getsales_rep_ref_fullname()
{
return $this->sales_rep_ref_fullname;
}

function getsales_tax_code_ref_listid()
{
return $this->sales_tax_code_ref_listid;
}

function getsales_tax_code_ref_fullname()
{
return $this->sales_tax_code_ref_fullname;
}

function gettax_code_ref_listid()
{
return $this->tax_code_ref_listid;
}

function gettax_code_ref_fullname()
{
return $this->tax_code_ref_fullname;
}

function getitem_sales_tax_ref_listid()
{
return $this->item_sales_tax_ref_listid;
}

function getitem_sales_tax_ref_fullname()
{
return $this->item_sales_tax_ref_fullname;
}

// **********************
// SETTER METHODS
// **********************


function setid($val)
{
$this->id =  $val;
}

function settimecreated($val)
{
$this->timecreated =  $val;
}

function settimemodified($val)
{
$this->timemodified =  $val;
}

function setname($val)
{
$this->name =  $val;
}

function setfullname($val)
{
$this->fullname =  $val;
}

function setfname($val)
{
$this->fname =  $val;
}

function setlname($val)
{
$this->lname =  $val;
}

function setsalutation($val)
{
$this->salutation =  $val;
}

function setaddress($val)
{
$this->address =  $val;
}

function setcity($val)
{
$this->city =  $val;
}

function setstate($val)
{
$this->state =  $val;
}

function setzipcode($val)
{
$this->zipcode =  $val;
}

function setcountry($val)
{
$this->country =  $val;
}

function setemail($val)
{
$this->email =  $val;
}

function setquickbooks_listid($val)
{
$this->quickbooks_listid =  $val;
}

function setquickbooks_editsequence($val)
{
$this->quickbooks_editsequence =  $val;
}

function setquickbooks_errnum($val)
{
$this->quickbooks_errnum =  $val;
}

function setquickbooks_errmsg($val)
{
$this->quickbooks_errmsg =  $val;
}

function setsales_rep_ref_listid($val)
{
$this->sales_rep_ref_listid =  $val;
}

function setsales_rep_ref_fullname($val)
{
$this->sales_rep_ref_fullname =  $val;
}

function setsales_tax_code_ref_listid($val)
{
$this->sales_tax_code_ref_listid =  $val;
}

function setsales_tax_code_ref_fullname($val)
{
$this->sales_tax_code_ref_fullname =  $val;
}

function settax_code_ref_listid($val)
{
$this->tax_code_ref_listid =  $val;
}

function settax_code_ref_fullname($val)
{
$this->tax_code_ref_fullname =  $val;
}

function setitem_sales_tax_ref_listid($val)
{
$this->item_sales_tax_ref_listid =  $val;
}

function setitem_sales_tax_ref_fullname($val)
{
$this->item_sales_tax_ref_fullname =  $val;
}

// ************************************************************************************
// SELECT busca igual en el campo estado retorna OK si existe el registro
//          retorna actualiza si es el mismo registro y tambien carga en la instancia
//          los valores de la lectura
// *************************************************************************************

    function buscaIgual_mycustomer() {
        $estado = 'ERR';
        $this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        try {
            $sql =  'SELECT * FROM my_customer_table WHERE quickbooks_listid = :clave ';
            $stmt = $this->db->prepare($sql);
            $stmt->bindParam(':clave', $_SESSION['mycustomer']['ListID']);
            $stmt->execute();
            $registro = $stmt->fetch(PDO::FETCH_ASSOC);
            if ( ! $registro){
                $this->estado = 'OK';
            } else {
                if ($registro['quickbooks_listid'] === $_SESSION['mycustomer']['ListID']) {
                $this->estado = 'ACTUALIZA';
                }
            }
            
        } catch(PDOException $e) {
            echo $e->getMessage();
        } 
    
    return $this->estado;
    }
// ************************************************************************************
// SELECT dependiendo de las condiones recibidas desde el programa llamado se parsea
//          el archivo json para cargar las comparaciones y tambien los nombres de las variables
//          para una lectura de todos los registros que cumplan la condicion
// *************************************************************************************

    function leetodos_mycustomer() {
        $estado = 'ERR';
        $this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        try {
            $sql =  'SELECT * FROM invoice WHERE TxnID = :clave ';
            $stmt = $this->db->prepare($sql);
            $stmt->bindParam(':clave', $_SESSION['mycustomer']['TxnID']);
            $stmt->execute();
            $registro = $stmt->fetchAll(PDO::FETCH_ASSOC);
            if ( ! $registro){
                $this->estado = 'OK';
            } else {
                $this->estado = 'TODOS';
            }
            
        } catch(PDOException $e) {
            echo $e->getMessage();
        } 
    
    return $this->estado;
    }
// **********************
// SELECT METHOD / LOAD
// **********************

function select_mycustomer()
{

$this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
	try {
$sql = 'SELECT * FROM my_customer_table WHERE id = :clave'; 
$stmt = $this->db->prepare($sql);
    $stmt->bindParam(":clave", $_SESSION['my_customer_table']['TxnID']);
        $stmt->execute();
	$registro = $stmt->fetch(PDO::FETCH_ASSOC);
	if ( ! $registro) {
		$this->estado = 'OK';
		return $this->estado;
	} else {
                
		if ($registro['TxnID'] === $_SESSION['invoice']['TxnID']) {
                    $this->estado = 'ACTUALIZA';
                    }
                    }
            
                } catch(PDOException $e) {
                    echo $e->getMessage();
                }
                
		$this->id = $registro['id'];

		$this->timecreated = $registro['timecreated'];

		$this->timemodified = $registro['timemodified'];

		$this->name = $registro['name'];

		$this->fullname = $registro['fullname'];

		$this->fname = $registro['fname'];

		$this->lname = $registro['lname'];

		$this->salutation = $registro['salutation'];

		$this->address = $registro['address'];

		$this->city = $registro['city'];

		$this->state = $registro['state'];

		$this->zipcode = $registro['zipcode'];

		$this->country = $registro['country'];

		$this->email = $registro['email'];

		$this->quickbooks_listid = $registro['quickbooks_listid'];

		$this->quickbooks_editsequence = $registro['quickbooks_editsequence'];

		$this->quickbooks_errnum = $registro['quickbooks_errnum'];

		$this->quickbooks_errmsg = $registro['quickbooks_errmsg'];

		$this->sales_rep_ref_listid = $registro['sales_rep_ref_listid'];

		$this->sales_rep_ref_fullname = $registro['sales_rep_ref_fullname'];

		$this->sales_tax_code_ref_listid = $registro['sales_tax_code_ref_listid'];

		$this->sales_tax_code_ref_fullname = $registro['sales_tax_code_ref_fullname'];

		$this->tax_code_ref_listid = $registro['tax_code_ref_listid'];

		$this->tax_code_ref_fullname = $registro['tax_code_ref_fullname'];

		$this->item_sales_tax_ref_listid = $registro['item_sales_tax_ref_listid'];

		$this->item_sales_tax_ref_fullname = $registro['item_sales_tax_ref_fullname'];


}

// *******************************
// UNSET METHOD / clean
// *******************************

function cleanSession_mycustomer()
{

                unset($_SESSION['mycustomer']['id']);
unset($_SESSION['mycustomer']['timecreated']);
unset($_SESSION['mycustomer']['timemodified']);
unset($_SESSION['mycustomer']['name']);
unset($_SESSION['mycustomer']['fullname']);
unset($_SESSION['mycustomer']['fname']);
unset($_SESSION['mycustomer']['lname']);
unset($_SESSION['mycustomer']['salutation']);
unset($_SESSION['mycustomer']['address']);
unset($_SESSION['mycustomer']['city']);
unset($_SESSION['mycustomer']['state']);
unset($_SESSION['mycustomer']['zipcode']);
unset($_SESSION['mycustomer']['country']);
unset($_SESSION['mycustomer']['email']);
unset($_SESSION['mycustomer']['quickbooks_listid']);
unset($_SESSION['mycustomer']['quickbooks_editsequence']);
unset($_SESSION['mycustomer']['quickbooks_errnum']);
unset($_SESSION['mycustomer']['quickbooks_errmsg']);
unset($_SESSION['mycustomer']['sales_rep_ref_listid']);
unset($_SESSION['mycustomer']['sales_rep_ref_fullname']);
unset($_SESSION['mycustomer']['sales_tax_code_ref_listid']);
unset($_SESSION['mycustomer']['sales_tax_code_ref_fullname']);
unset($_SESSION['mycustomer']['tax_code_ref_listid']);
unset($_SESSION['mycustomer']['tax_code_ref_fullname']);
unset($_SESSION['mycustomer']['item_sales_tax_ref_listid']);
unset($_SESSION['mycustomer']['item_sales_tax_ref_fullname']);


            }

// **********************
// DELETE
// **********************

function delete_mycustomer($id)
{


}

// **********************
// UPDATE
// **********************

function update_mycustomer()
{
    $this->estado = 'ERR';
	 $this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            try {
	$sql = 'UPDATE my_customer_table SET timecreated=$this->timecreated, timemodified=$this->timemodified, name=$this->name, fullname=$this->fullname, fname=$this->fname, lname=$this->lname, salutation=$this->salutation, address=$this->address, city=$this->city, state=$this->state, zipcode=$this->zipcode, country=$this->country, email=$this->email, quickbooks_listid=$this->quickbooks_listid, quickbooks_editsequence=$this->quickbooks_editsequence, quickbooks_errnum=$this->quickbooks_errnum, quickbooks_errmsg=$this->quickbooks_errmsg, sales_rep_ref_listid=$this->sales_rep_ref_listid, sales_rep_ref_fullname=$this->sales_rep_ref_fullname, sales_tax_code_ref_listid=$this->sales_tax_code_ref_listid, sales_tax_code_ref_fullname=$this->sales_tax_code_ref_fullname, tax_code_ref_listid=$this->tax_code_ref_listid, tax_code_ref_fullname=$this->tax_code_ref_fullname, item_sales_tax_ref_listid=$this->item_sales_tax_ref_listid, item_sales_tax_ref_fullname=$this->item_sales_tax_ref_fullname, WHERE id = :clave;'; 
	$stmt = $this->db->prepare($sql);
        
	$stmt->bindParam(':clave', $_SESSION['invoice']['TxnID']);
	$stmt->execute();
     } catch(PDOException $e) {
}
     }

// ---------------------------------------------------------
// Actualiza tabla con la opcion del PDO bindparam
// ---------------------------------------------------------

function actualiza_mycustomer()
{
    $this->estado = 'ERR';
	 $this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            try {
	$sql = 'UPDATE my_customer_table SET timecreated=:timecreated, timemodified=:timemodified, name=:name, fullname=:fullname, fname=:fname, lname=:lname, salutation=:salutation, address=:address, city=:city, state=:state, zipcode=:zipcode, country=:country, email=:email, quickbooks_listid=:quickbooks_listid, quickbooks_editsequence=:quickbooks_editsequence, quickbooks_errnum=:quickbooks_errnum, quickbooks_errmsg=:quickbooks_errmsg, sales_rep_ref_listid=:sales_rep_ref_listid, sales_rep_ref_fullname=:sales_rep_ref_fullname, sales_tax_code_ref_listid=:sales_tax_code_ref_listid, sales_tax_code_ref_fullname=:sales_tax_code_ref_fullname, tax_code_ref_listid=:tax_code_ref_listid, tax_code_ref_fullname=:tax_code_ref_fullname, item_sales_tax_ref_listid=:item_sales_tax_ref_listid, item_sales_tax_ref_fullname=:item_sales_tax_ref_fullname, WHERE quickbooks_listid = :clave;'; 
	$stmt = $this->db->prepare($sql);
	$stmt->bindParam(':timecreated', $_SESSION['mycustomer']['TimeCreated'] );
	$stmt->bindParam(':timemodified', $_SESSION['mycustomer']['TimeModified'] );
	$stmt->bindParam(':name', $_SESSION['mycustomer']['Name'] );
	$stmt->bindParam(':fullname', $_SESSION['mycustomer']['FullName'] );
	$stmt->bindParam(':fname', $_SESSION['mycustomer']['FirstName'] );
	$stmt->bindParam(':lname', $_SESSION['mycustomer']['LastName'] );
	$stmt->bindParam(':salutation', $_SESSION['mycustomer']['Salutation'] );
	$stmt->bindParam(':address', $_SESSION['mycustomer']['BillAddress_Addr1'] );
	$stmt->bindParam(':city', $_SESSION['mycustomer']['BillAddress_City'] );
	$stmt->bindParam(':state', $_SESSION['mycustomer']['BillAddress_State'] );
	$stmt->bindParam(':zipcode', $_SESSION['mycustomer']['BillAddress_PostalCode'] );
	$stmt->bindParam(':country', $_SESSION['mycustomer']['BillAddress_Country'] );
	$stmt->bindParam(':email', $_SESSION['mycustomer']['Email'] );
	$stmt->bindParam(':quickbooks_listid', $_SESSION['mycustomer']['ListID'] );
	$stmt->bindParam(':quickbooks_editsequence', $_SESSION['mycustomer']['EditSequence'] );
	$stmt->bindParam(':quickbooks_errnum', $_SESSION['mycustomer']['TermsRef_ListID'] );
	$stmt->bindParam(':quickbooks_errmsg', $_SESSION['mycustomer']['TermsRef_FullName'] );
	$stmt->bindParam(':sales_rep_ref_listid', $_SESSION['mycustomer']['SalesRepRef_ListID'] );
	$stmt->bindParam(':sales_rep_ref_fullname', $_SESSION['mycustomer']['SalesRepRef_FullName'] );
	$stmt->bindParam(':sales_tax_code_ref_listid', $_SESSION['mycustomer']['SalesTaxCodeRef_ListID'] );
	$stmt->bindParam(':sales_tax_code_ref_fullname', $_SESSION['mycustomer']['SalesTaxCodeRef_FullName'] );
	$stmt->bindParam(':tax_code_ref_listid', $_SESSION['mycustomer']['SalesTaxCodeRef_ListID'] );
	$stmt->bindParam(':tax_code_ref_fullname', $_SESSION['mycustomer']['SalesTaxCodeRef_FullName'] );
	$stmt->bindParam(':item_sales_tax_ref_listid', $_SESSION['mycustomer']['ItemSalesTaxRef_ListID'] );
	$stmt->bindParam(':item_sales_tax_ref_fullname', $_SESSION['mycustomer']['ItemSalesTaxRef_FullName'] );
	$stmt->bindParam(':clave', $_SESSION['mycustomer']['ListID']);
	$stmt->execute();
     } catch(PDOException $e) {
}
     }

}
?>
<!-- end of generated class -->
